### PR TITLE
Fix Indent if-then-colon #5929

### LINKED ISSUE #5929: Auto-indent doesn't account for shortcut if with colon
#### Rubberduck version information
* Rubberduck version: 2.5.2.5906
* Operating System: Microsoft Windows NT 10.0.19044.0 x64
* Host Product: Microsoft Office x64
* Host Version: 16.0.14701.20262
* Host Executable: EXCEL.EXE;

#### Description
The indentation feature doesn't account for shortcut if statements using ":" and instead indents everything after it.

#### To Reproduce
Using auto-indent on the following:
```
Dim Test As Boolean

If Test Then
Debug.Print "TestTrue"
Else
Debug.Print "TestFalse"
End If

If Test Then: Debug.Print "ShortTestTrue"
Debug.Print "Shouldn't indent"
Debug.Print "Also shouldn't indent"
```
gets this:
```
Dim Test As Boolean

If Test Then
    Debug.Print "TestTrue"
Else
    Debug.Print "TestFalse"
End If

If Test Then: Debug.Print "ShortTestTrue"
    Debug.Print "Shouldn't indent"
    Debug.Print "Also shouldn't indent"
```

#### Expected behavior
The indentation should detect the colon after the "Then" as sign of a shortcut if-statement and don't add indentation to all following lines like this:
```
Dim Test As Boolean

If Test Then
    Debug.Print "TestTrue"
Else
    Debug.Print "TestFalse"
End If

If Test Then: Debug.Print "ShortTestTrue"
Debug.Print "Shouldn't indent"
Debug.Print "Also shouldn't indent"
```

#### Additional context
In a few other issues I've read to avoid duplicates I think I got that the indenter doesn't really know about the code's meaning itself and as such is queued for a complete rewrite anyway, but maybe this is easy enough to fix and/or helps finding kinks in the new implementation.

### PR DESCRIPTION
**Pull request by awb95**
Fix #5929 .
The 'then'-Statement triggered an Indent even tough the line got continued with ':'.
Edited Test for IfThenElseOnSameLine to contain valid VBA Code and check #5929

### CODE REVIEW

File: Rubberduck.SmartIndenter/LogicalCodeLine.cs [hunk 1]
```diff
@@ -51,9 +51,16 @@ public int NextLineIndents
                 {
                     return 0;
                 }
-                return _rebuilt.Segments.Count() < 2
+                var indents = _rebuilt.Segments.Count() < 2
                     ? _rebuilt.NextLineIndents
                     : _rebuilt.Segments.Select(s => new AbsoluteCodeLine(s, _settings)).Select(a => a.NextLineIndents).Sum();
+
+                if (_rebuilt.ContaisIfThenWithColonNoElse)
```
Comment (retailcoder) [inline Rubberduck.SmartIndenter/LogicalCodeLine.cs:58]:
```suggestion
                if (_rebuilt.ContainsIfThenWithColonNoElse)
```

**Review by retailcoder — APPROVED** [review]

**Review by retailcoder — CHANGES_REQUESTED** [review]
LGTM, just a typo needs fixing

File: Rubberduck.SmartIndenter/AbsoluteCodeLine.cs [hunk 2]
```diff
@@ -192,6 +193,8 @@ public bool IsProcedureEnd
 
         public bool IsEmpty => Original.Trim().Length == 0;
 
+        public bool ContaisIfThenWithColonNoElse => IfThenWithColonNoElseRegex.IsMatch(_code);
```
Comment (retailcoder) [inline Rubberduck.SmartIndenter/AbsoluteCodeLine.cs:196]:
```suggestion
        public bool ContainsIfThenWithColonNoElse => IfThenWithColonNoElseRegex.IsMatch(_code);
```

**Review by retailcoder — APPROVED** [review]
