### PR TITLE
Fix rename of UDTs

### LINKED ISSUE #4056: Refactor/rename of type within a class doesn't change the identifier of the type definition itself
This may be similar/rehash of #3468 / #3469 (please let me know if I should be just commenting on that to re-open?).  I believe my installed RD version should incorporate the fix referenced there:

Version 2.2.6720.27013
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9330.2087
Host Executable: MSACCESS.EXE

However, the following code in a blank database and class module did not result in a rename of the UDT type name itself:

```
Private Type t_ToBeRenamed  'Cursor here, RD-->Refactor-->Rename, t_ToBeRenamed stays the same
    Blank as object
End Type

Private Sub ASub(aParam as t_ToBeRenamed) ' does get renamed to the new name
End Sub
```

### PR DESCRIPTION
**Pull request by MDoerner**
This PR closes #4056 

I took the third option outlined in the issue and it was much more straight forward than expected. Apparently, nothing was really using the separate contextx for the visibility.

I also improved the handling of com wrappers in `VBENativeServices`, which was leaking tons of wrappers. This had a positive effect on the com issues at the shutdown of RD, as far as I could judge in the debugger.

### CODE REVIEW

**Comment by Vogel612** [comment]
could we have a testcase for references to the UDT in a different module, please? Aside from that, this looks great

**Comment by MDoerner** [comment]
I will see whether I can add that test case tonight. However, renaming of references never has been broken; only the declaration failed to get renamed.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 1]
```diff
@@ -64,6 +63,7 @@ public static void UnhookEvents()
                     info.Subclass.Dispose();
                 }
                 VBEEvents.Terminate();
+                _vbe = null;
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Do we need to dispose this first?

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 2]
```diff
@@ -188,12 +199,29 @@ private static void OnWindowFocusChange(object sender, WindowChangedEventArgs ev
...
+                    foreach (var pane in panes)
+                    {
+                        using (var window = pane.Window)
+                        {
+                            if (window.Caption.Equals(caption))
+                            {
+                                return pane;
+                            }
+                        }
+                        pane.Dispose();
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Don't we want to use `using` for `pane`, too? Otherwise when an exception is thrown inside the `window`'s `using` block, the `pane` will get leaked.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 3]
```diff
@@ -207,15 +235,23 @@ private static ICodePane GetCodePaneFromHwnd(IntPtr hwnd)
...
             using (var windows = _vbe.Windows)
             {
-                return windows.FirstOrDefault(x => x.Caption.Equals(caption));
+                foreach (var window in windows)
+                {
+                    if (window.Caption.Equals(caption))
+                    {
+                        return window;
+                    }
+                    window.Dispose();
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Same concern RE: exceptions causing leaks because `window.Dispose()` won't be `finally`'d.

File: RubberduckTests/Refactoring/RenameTests.cs [hunk 4]
```diff
@@ -1766,6 +1766,123 @@ MsgBox CStr(CranApple)
...
+        [Category("Rename")]
+        public void RenameRefactoring_RenamePublicUDT()
+        {
+            var tdo = new RenameTestsDataObject(selection: "UserType", newName: "NewUserType");
+            var inputOutput = new RenameTestModuleDefinition("Module1", ComponentType.StandardModule)
+            {
+                Input =
+                    @"Option Explicit
+
+Public Type UserType|
```
Comment (bclothier) [inline RubberduckTests/Refactoring/RenameTests.cs]: Not related to the PR but I really wished we had used that faux cursor idea everywhere else instead of hard-coding the selections in the other unit tests. I will make a note to adapt that for other unit tests I'll be working on.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 1 above)
Comment (MDoerner) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: No, it has been passed in from the outside. More precisely, this is the original COM wrapper from the entry point.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 2 above)
Comment (MDoerner) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: The problem is that you do not want to dispose the pane returned.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 3 above)
Comment (MDoerner) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: As above, if you put the dispose in the finally block, you dispose the return value.

File: RubberduckTests/Refactoring/RenameTests.cs (hunk 4 above)
Comment (retailcoder) [reply RubberduckTests/Refactoring/RenameTests.cs]: Ha! I was thinking to do *exactly* that for the AC tests!

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 3 above)
Comment (MDoerner) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: I think I have an idea how to handle this. However, that does not make the code prettier.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 5]
```diff
@@ -1,7 +1,6 @@
 ﻿using System;
 using System.Collections.Generic;
 using System.Diagnostics;
-using System.Linq;
```
Comment (retailcoder) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: :+1:

**Comment by bclothier** [comment]
Just as a FYI - the improvement in COM release does not address the ghost process w/ Access after exiting; this still exists.
