### PR TITLE
CodeBuilder - Provide 'casing friendly' default property RHS parameter name

### LINKED ISSUE #5552: EncapsulateField Refactoring default 'value' parameter causes casing change to built-in object's "Value" member
**Rubberduck version information**
Version 2.5.0.25332
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.13029.20308
Host Executable: EXCEL.EXE

**To Reproduce**
1. Given:
```
Option Explicit

Public mTestField As Long

Public Sub Test()
    Dim rg As Range
    Dim wksht As Worksheet
    Set wksht = Application.Worksheets("Sheet1")
    Set rg = wksht.Range("A1")
    mTestField = rg.Value
End Sub
```

2. Run `EncapsulateField Refactoring` on `mTestField`.  See casing change to `Range.Value` member.

```
Option Explicit

Private mTestField As Long

Public Property Get TestField() As Long
    TestField = mTestField
End Property

Public Property Let TestField(ByVal value As Long)
    mTestField = value
End Property

Public Sub Test()
    Dim rg As Range
    Dim wksht As Worksheet
    Set wksht = Application.Worksheets("Sheet1")
    Set rg = wksht.Range("A1")
    TestField = rg.value
End Sub

```

**Expected behavior**
Need to introduce a Property Let/Set parameter identifier that avoids existing names (or existing names with different casing).  
A couple options come to mind:
1. Pick a different hard-coded default: like "newValue"  
2. Avoid casing issues more generally by generating a parameter name from the Property identifier e.g,: 
```
Property Let TestField(ByVal testFieldValue As Long)
      mTestField = testFieldValue 
End Property
```
Based on some quick experiments, introducing an identifier that matches _any_ existing identifier (with different casing), changes the casing of existing identifiers everywhere in the `Project` (`Procedure`, `Module` scoping is irrelevant).  To generate a _casing-safe_ parameter might require finding a name that is unique throughout the loaded `Projects`.

### PR DESCRIPTION
**Pull request by BZngr**
Closes #5552.

This PR modifies the default property RHS parameter IdentifierName.  The previous default ('value') creates casing issues(#5552).  The PR proposes to resolve the issue by using a custom parameter IdentifierName for each generated property of the form "propertyIdentifierValue".  (e.g., `Property Let Foo(ByVal fooValue As Long)`).

### CODE REVIEW

File: Rubberduck.Refactorings/EncapsulateField/FieldCandidates/EncapsulateFieldCandidate.cs [hunk 1]
```diff
@@ -47,11 +45,13 @@ public class EncapsulateFieldCandidate : IEncapsulateFieldCandidate
         protected int _hashCode;
         private string _identifierName;
         protected EncapsulationIdentifiers _fieldAndProperty;
+        private Func<string, string> _paramNameBuilder;
 
-        public EncapsulateFieldCandidate(Declaration declaration, IValidateVBAIdentifiers identifierValidator)
+        public EncapsulateFieldCandidate(Declaration declaration, IValidateVBAIdentifiers identifierValidator, Func<string, string> paramNameBuilder)
```
Comment (MDoerner) [inline Rubberduck.Refactorings/EncapsulateField/FieldCandidates/EncapsulateFieldCandidate.cs:50]: I am not a fan of shortening parameter and variable names.
However, here it is good-enough as it is.

File: RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldTests.cs [hunk 2]
```diff
@@ -21,6 +21,8 @@ public class EncapsulateFieldTests : InteractiveRefactoringTestBase<IEncapsulate
     {
         private EncapsulateFieldTestSupport Support { get; } = new EncapsulateFieldTestSupport();
 
+        private static Func<string, string> Param = EncapsulateFieldTestSupport.ParamNameBuilder;
```
Comment (MDoerner) [inline RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldTests.cs:24]: I would prefer something like `RhsParameterNameBuilder`, but it seems good-enough here in the tests.

File: RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldTests.cs [hunk 3]
```diff
@@ -363,26 +365,26 @@ public void EncapsulatePrivateFieldInList()
             const string inputCode =
                 @"Private fi|zz As Integer, fuzz As Integer, fazz As Integer";
 
-            const string expectedCode =
-                @"
-Private fizz_1 As Integer, fuzz As Integer, fazz As Integer
+//            const string expectedCode =
```
Comment (MDoerner) [inline RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldTests.cs:368]: Commented out code?
Please remove or uncomment, in case this was meant to be commented out only temporarily.

File: RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldTests.cs [hunk 4]
```diff
@@ -395,24 +397,24 @@ public void EncapsulatePrivateField_Defaults()
             const string inputCode =
                 @"|Private fizz As Integer";
 
-            const string expectedCode =
-                @"Private fizz_1 As Integer
+//            const string expectedCode =
```
Comment (MDoerner) [inline RubberduckTests/Refactoring/EncapsulateField/EncapsulateFieldTests.cs:400]: commented out code

File: RubberduckTests/Refactoring/EncapsulateField/EncapsulateUsingStateUDTTests.cs [hunk 5]
```diff
@@ -17,6 +17,8 @@ public class EncapsulateUsingStateUDTTests : InteractiveRefactoringTestBase<IEnc
     {
         private EncapsulateFieldTestSupport Support { get; } = new EncapsulateFieldTestSupport();
 
+        private static Func<string, string> Param = EncapsulateFieldTestSupport.ParamNameBuilder;
```
Comment (MDoerner) [inline RubberduckTests/Refactoring/EncapsulateField/EncapsulateUsingStateUDTTests.cs:20]: See above

File: RubberduckTests/Refactoring/EncapsulateField/EncapsulatedUDTFieldTests.cs [hunk 6]
```diff
@@ -14,6 +15,8 @@ public class EncapsulatedUDTFieldTests : InteractiveRefactoringTestBase<IEncapsu
     {
         private EncapsulateFieldTestSupport Support { get; } = new EncapsulateFieldTestSupport();
 
+        private static Func<string, string> Param = EncapsulateFieldTestSupport.ParamNameBuilder;
```
Comment (MDoerner) [inline RubberduckTests/Refactoring/EncapsulateField/EncapsulatedUDTFieldTests.cs:18]: See above

**Comment by BZngr** [comment]
@MDoerner  Thanks for reviewing this PR so it can be included in the next release.  I preferred your naming suggestions - so they have been incorporated.  All other comments addressed as well.
