### PR TITLE
Sort out dlls for different versions.

### LINKED ISSUE #4516: VB6, Fakes and Easyhook
In testing it seems that VB6 will not necessarily load `vbe6.dll`, but rather `msvmvb6.dll` which is very similar library. 

The present logic switches based on the VBE's `Version` property. This is no longer sufficient to handle VB6 support. For that reason, fakes will not work in VB6. We need a way of detecting whether we are loaded inside a VB6 host vs VBA host and thus switch the DLL name accordingly.

### PR DESCRIPTION
**Pull request by comintern**
Closes #4516

### CODE REVIEW

File: Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs [hunk 1]
```diff
@@ -0,0 +1,98 @@
+﻿using System;
+using System.Runtime.InteropServices;
+using Rubberduck.VBEditor.VbeRuntime;
+
+namespace Rubberduck.VBEditor.VBERuntime
+{
+    internal class Vb6NativeApi : IVbeNativeApi
+    {
+        private const string _dllName = "vba6.dll";
```
Comment (bclothier) [inline Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs]: I still worry that this might not work if the vb6 loads `msvmvb6.dll` as it did in my instance. I could not locate the vbe6.dll in the PE unless I'm doing it wrong.

File: Rubberduck.VBEEditor/VBERuntime/Settings/VBESettings.cs [hunk 2]
```diff
@@ -7,26 +9,27 @@ namespace Rubberduck.VBEditor.VbeRuntime.Settings
...
             {
-                switch (VbeDllVersion.GetCurrentVersion(vbe))
+                Version = VbeDllVersion.GetCurrentVersion(vbe);
+                switch (Version)
                 {
+                    case DllVersion.Vbe7:
                     case DllVersion.Vbe6:
-                        Version = DllVersion.Vbe6;
-                        _activeRegistryRootPath = Vbe6SettingPath;
+                        _activeRegistryRootPath = string.Format(VbeSettingPathTemplate, vbe.Version);
```
Comment (bclothier) [inline Rubberduck.VBEEditor/VBERuntime/Settings/VBESettings.cs]: Much more prettier! 👍

File: Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs (hunk 1 above)
Comment (comintern) [reply Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs]: Did it *only* load `msvmvb6.dll`? I could have sworn that pretty much everything that targets that run-time forwards calls through to it.

Comment (bclothier) [reply Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs]: when I looked, yes. I only created a empty vb6 exe project, then immediately created a test module. Ran PE and it didn't even show vbe6.dll unless I completely missed it.

File: Rubberduck.VBEEditor/VBERuntime/VBEDllVersion.cs [hunk 3]
```diff
@@ -18,7 +19,7 @@ public static DllVersion GetCurrentVersion(IVBE vbe)
                 switch (int.Parse(vbe.Version.Split('.')[0]))
                 {
                     case 6:
-                        return DllVersion.Vbe6;
+                        return vbe.GetType().Namespace?.EndsWith("VB6") ?? false ? DllVersion.Vb98 : DllVersion.Vbe6;
```
Comment (mansellan) [inline Rubberduck.VBEEditor/VBERuntime/VBEDllVersion.cs]:
```suggestion
                        return vbe.Kind == VBEKind.Standalone ? DllVersion.Vb98 : DllVersion.Vbe6;
```

Comment (comintern) [reply Rubberduck.VBEEditor/VBERuntime/VBEDllVersion.cs]: Good call - completely missed that.

File: Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs [hunk 4]
```diff
@@ -37,36 +38,30 @@ private static IVbeNativeApi InitializeRuntime()
...
                 catch
                 {
-                    // we shouldn't be here.... Rubberduck is a VBA add-in, so how the heck could it have loaded without a VBE dll?!?
-                    throw new InvalidOperationException("Cannot execute DoEvents; the VBE dll could not be located.");
+                    // ignored
                 }
             }
-
-            return _version != DllVersion.Unknown ? runtime : null;
+            // we shouldn't be here.... Rubberduck is a VBA add-in, so how the heck could it have loaded without a VBE dll?!?
```
Comment (retailcoder) [inline Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs]: Rubberduck is a *VB**E*** add-in now though :wink:

File: Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs (hunk 1 above)
Comment (retailcoder) [reply Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs]: `vba6.dll` for `Vb6NativeApi`? I'm missing something.. or is it a typo?

Comment (bclothier) [reply Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs]: I also see that's something of a red herring --- VBA will load `vbe6` whereas VB6 will load `vba6`. Had to squint a bit more...

File: Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs [hunk 5]
```diff
@@ -37,36 +38,30 @@ private static IVbeNativeApi InitializeRuntime()
...
+            throw new InvalidOperationException("Cannot execute DoEvents; the VBE dll could not be located.");
```
Comment (bclothier) [inline Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs]: See, one bad thing about editing a hacked code made by a hack is that you inherit all the hack's silliness, including hard-coding a name of method that was no longer used. We are calling `Timer`, not `DoEvents` here. Really, I should have written it as `Cannot execute a method from VBE dll; the VBE dll could not be located.`.

File: Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs (hunk 1 above)
Comment (retailcoder) [reply Rubberduck.VBEEditor/VBERuntime/Vb6NativeApi.cs]: > VBA will load vbe6 whereas VB6 will load vba6

An explanatory comment (with credits to MS?) to that effect might help relieving stuck eyebrows.

File: Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs (hunk 5 above)
Comment (comintern) [reply Rubberduck.VBEEditor/VbeRuntime/VbeNativeApiAccessor.cs]: So when a hack edits a hack made by a hack...  NVM, I'll push a new comment over lunch.
