### PR TITLE
Avoid NREs in UnreachableCaseInspection

### LINKED ISSUE #4659: NRE in UnreachableCaseInspection
I noticed this while I was meatbagging the Code Explorer. The expression parser in the `UnreachableCaseInspection` apparently has problems with enumerations that use built-in constants. This MCVE...

```
Enum Fubar
    Foo = vbObjectError + 1
    Bar = vbObjectError + 2
End Enum

Sub Example()
    Select Case 42
        Case Fubar.Foo
            Debug.Print "Foo"
        Case Fubar.Bar
            Debug.Print "Bar"
    End Select
End Sub
```
...results in this error:

```
2018-12-18 17:19:14.9769;WARN-2.3.6926.13270;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 324
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 291
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 271
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 135
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitBinaryOpEvaluationContext(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 167
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 116
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 339
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.LoadEnumMemberValues() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 393
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor..ctor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 idRefRetriever) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 45
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.CreateParseTreeValueVisitor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 func) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 84
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 55
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 324
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetContextValue(ParserRuleContext context, String& declaredTypeName, String& expressionValue) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 291
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetLExprValue(LExprContext lExprContext, String& expressionValue, String& declaredTypeName) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 271
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 135
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 96
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 247
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitBinaryOpEvaluationContext(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 167
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 116
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.GetConstantContextValueToken(ParserRuleContext context) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 339
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.LoadEnumMemberValues() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 393
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor..ctor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 idRefRetriever) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 45
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.CreateParseTreeValueVisitor(IParseTreeValueFactory valueFactory, List`1 allEnums, Func`2 func) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 84
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 55
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 166
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\Rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 188
```

### LINKED ISSUE #4680: Unreachable Case Inspection does not correctly evaluate strings with VBA String constants
Unreachable Case Inspection does not flag cases like the following that include control characters :

```
Sub Foo(value As String)
    Select Case value
        Case ""Hello"" + vbNewLine + ""World""
            MsgBox ""vbNewLine version""
        Case ""Hello"" + vbCr + vbLf + ""World"" 'unreachable
            MsgBox ""vbCr + vbLf version""
        Case ""Reachable""
            MsgBox ""Reachable""
    End Select
End Sub
```

### PR DESCRIPTION
**Pull request by BZngr**
Closes #4659 
Closes #4680

### CODE REVIEW

File: Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs [hunk 1]
```diff
@@ -286,6 +300,25 @@ private void GetContextValue(ParserRuleContext context, out string declaredTypeN
                 expressionValue = rangeClauseIdentifierReference.IdentifierName;
                 declaredTypeName = GetBaseTypeForDeclaration(declaration);
 
+                if (declaration is ValuedDeclaration valuedDeclaration)
+                {
+                    expressionValue = valuedDeclaration.Expression;
+                    declaredTypeName = GetBaseTypeForDeclaration(declaration);
+                    if (IsVBStringConstant(expressionValue))
```
Comment (bclothier) [inline Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs]: I might be missing something but what if I have a user defined string constant? Shouldn't it get the same treatment as the built-in string constants?

Comment (BZngr) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs]: I'm intentionally short circuiting the built-in string constants because I've yet to find a workable approach.  My goal with this PR is to address the NREs with respect to non-string built-in constants.  The basic problem to solve for strings is that the built-in  string constants like vbCr have content but are zero-length.  The 'zero-length-ness' is not handled properly by the existing string constant code that addresses user-defined constants.  Handling/Comparing the built-in string constants is (based on my initial attempts) a much more difficult change.

File: Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs [hunk 2]
```diff
@@ -34,6 +34,20 @@ public EnumMember(VBAParser.EnumerationStmt_ConstantContext constContext, long i
         private List<VBAParser.EnumerationStmtContext> _enumStmtContexts;
         private List<EnumMember> _enumMembers;
 
+        private static List<KeyValuePair<string, string>> _vbStringConstants = new List<KeyValuePair<string, string>>()
+        {
+            new KeyValuePair<string, string>(Tokens.vbBack, ((char)8).ToString()),
+            new KeyValuePair<string, string>(Tokens.vbCr, ((char)13).ToString()),
+            new KeyValuePair<string, string>(Tokens.vbCrLf, ((char)13).ToString() + ((char)10).ToString()),
+            new KeyValuePair<string, string>(Tokens.vbLf, ((char)10).ToString()),
```
Comment (Vogel612) [inline Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs]: how about "\r", "\r\n", "\n"?

Comment (BZngr) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/UnreachableCaseInspection/ParseTreeValueVisitor.cs]: Good point....control character literal detection has been added.

**Comment by BZngr** [comment]
Resolves #4680 - addresses comparisons for strings with VBAString constants (non-printing control characters) in addition to vbObjectError.
