### PR TITLE
Hacktoberfest parser fixes

### LINKED ISSUE #2679: `Debug.Print/Assert` should be treated as 3 keywords rather than `Debug` is Class, `Print/Assert` is Method
RD currently treats `Debug` as a dummy class, and `Print` and `Assert` as dummy methods.

You can't declare a type of `Debug`, and you can't use `With Debug`, so it's not a class. You can't use `Debug` without using `Print` or `Assert`, and you can't use `Print` (as you do when using `Debug`) or `Assert` *without* using `Debug`.

Line continuations make for slight complications.

`Debug`, `Print` and `Assert` should be treated as keywords by RD.

### LINKED ISSUE #4888: Support for semicolon on object.print
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.4.1.4627
    Operating System: Win 10
    Host Product: Microsoft Visual Basic 6.0

**Description**
It seems vb6 allows a semi colon on the Print line to suppress CRLF. It seems to be an exception but it is making parsing fail on my [very old and large] code base.

more info: https://stackoverflow.com/questions/9290731/what-is-the-effect-of-a-semicolon-at-the-end-of-a-line

**Logfile**
```
2019-04-02 16:40:03.7484;ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.ModuleParser;Syntax error; offending token ';' at line 746, column 21 in the CodePaneCode version of module modGeneral.;
2019-04-02 16:40:03.7484;DEBUG-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.ModuleParser;SyntaxErrorException thrown in thread 10, ParseTaskID f8b54930-1b42-4137-9da1-c1dfbab69269.;Rubberduck.Parsing.VBA.Parsing.ParsingExceptions.MainParseSyntaxErrorException: extraneous input ';' expecting {<EOF>, ':', REM, NEWLINE, ''', WS, LINE_CONTINUATION}
   at Rubberduck.Parsing.VBA.Parsing.ParsingExceptions.MainParseExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ParsingExceptions\MainParseExceptionErrorListener.cs:line 14
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.SingleTokenDeletion(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 20219
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 2303
   at Rubberduck.Parsing.Grammar.VBAParser.ifStmt() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 8893
   at Rubberduck.Parsing.Grammar.VBAParser.mainBlockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 2707
   at Rubberduck.Parsing.Grammar.VBAParser.blockStmt() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 2461
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 2302
   at Rubberduck.Parsing.Grammar.VBAParser.subStmt() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 12721
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 2238
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 2131
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 446
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 334
   at Rubberduck.Parsing.VBA.Parsing.VBATokenStreamParser.Parse(ITokenStream tokenStream, PredictionMode predictionMode, IParserErrorListener errorListener) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\VBATokenStreamParser.cs:line 21
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase.ParseLl(String moduleName, ITokenStream tokenStream, CodeKind codeKind) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserBase.cs:line 75
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase.ParseWithFallBack(String moduleName, CommonTokenStream tokenStream, CodeKind codeKind) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserBase.cs:line 52
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase.Parse(String moduleName, CommonTokenStream tokenStream, CodeKind codeKind, ParserMode parserMode) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserBase.cs:line 32
   at Rubberduck.Parsing.VBA.Parsing.TokenStreamParserStringParserAdapterWithPreprocessing.Parse(String moduleName, String projectId, String code, CancellationToken token, CodeKind codeKind, ParserMode parserMode) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\TokenStreamParserStringParserAdapterWithPreprocessing.cs:line 29
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.CodePanePassResults(QualifiedModuleName module, CancellationToken token, TokenStreamRewriter rewriter) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 165
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.ParseInternal(QualifiedModuleName module, CancellationToken cancellationToken, TokenStreamRewriter rewriter, Guid taskId) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 84
   at Rubberduck.Parsing.VBA.Parsing.ModuleParser.Parse(QualifiedModuleName module, CancellationToken cancellationToken, TokenStreamRewriter rewriter) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\Parsing\ModuleParser.cs:line 40
Token: ; at L746C21
Kind of parsed code: CodePaneCode
Component: modGeneral (code pane version)
ParseType: Main parse
```

**Additional context**
Basically the line causing the issue is
```vb6
obj.Print a$;
```

### LINKED ISSUE #4983: Floating-point literals with comma decimal separator gives parsing error
**Rubberduck Version:** 

```
2019-06-03 12:06:23.8281;INFO-2.4.1.4627;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.4.1.4627 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: Visual Basic x86
	Host Version: 6.00.9782
	Host Executable: VB6.EXE;
```

**Description**
There was already a bug with this problem fixed in #1178.
My problem is that our source code is totally mixed with
FontSize        =   8,25
and
FontSize        =   8.25
also in the same files. VB doesn't have any problems with it, but RD gives many parsing errors.

**To Reproduce**
Create a form with 2 TextBoxes, manually edit the file and change FontSize.
I think that happened a long time ago with different Windows and VB6 language
versions.

The code looks like this:

```vb6
_ExtentX        =   9393
_ExtentY        =   5980
FontSize        =   8,25
TextVertical    =   1
TextHorizontal  =   0
PictureVertical =   0
PictureHorizontal=   0
Begin VB.CheckBox Check1
   Appearance      =   0  'Flat
   BackColor       =   &H00E2D3C9&
   Caption         =   "Check1"
   ForeColor       =   &H80000008&
   Height          =   225
   Left            =   705
   TabIndex        =   5
   Top             =   90
   Width           =   3750
End
Begin MSForms.TextBox Text1
   Appearance      =   0  'Flat
   BorderStyle     =   0  'None
   BeginProperty Font
      Name            =   "MS Sans Serif"
      Size            =   8.25
      Charset         =   8
      Weight          =   700
      Underline       =   0  'False
      Italic          =   0  'False
      Strikethrough   =   0  'False
   EndProperty
   Height          =   2535
End
```

**Expected behavior**
RD should parse both values correctly

**Logfile**
```
2019-06-03 12:06:50.2190;WARN-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase;SLL mode failed while parsing the AttributesCode version of module FRM_CHARLOCK at symbol , at L20C28. Retrying using LL.;
2019-06-03 12:06:50.2995;ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.ModuleParser;Syntax error; offending token ',' at line 20, column 28 in the AttributesCode version of module FRM_CHARLOCK.;
2019-06-03 12:06:51.0552;WARN-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.TokenStreamParserBase;SLL mode failed while parsing the AttributesCode version of module FRM_CHARGE at symbol , at L22C28. Retrying using LL.;
```

### LINKED ISSUE #5028: Can I add attributes to items with conditional compilation?
I'm trying to add '@Description attributes to api declarations with conditional compilation, like this:

```
'@Description("API: Destination and Source can be byVal pointers or byRef variables, length is LenB(dataType)")
#If Win64 Then
    Private Declare PtrSafe Sub CopyMemory Lib "kernel32.dll" Alias "RtlMoveMemory" (ByRef Destination As Any, ByRef Source As Any, ByVal length As Long)
#Else
    Private Declare Sub CopyMemory Lib "kernel32.dll" Alias "RtlMoveMemory" (ByRef Destination As Any, ByRef Source As Any, ByVal length As Long)
#End If
``` 

The inspections detect it fine but the quickfix does nothing, is this sort of thing supported?

### PR DESCRIPTION
**Pull request by MDoerner**
Closes #5028 
Closes #4983 
Closes #4888 
Closes #2679

This PR contains some grammar and parser fixes for the issues above, i.e. allows the parser to deal with VB6's object print statement, allows simple German style floating point literals in form properties and enables attibutes and attribute annotations on declare statements.

Moreover, it makes attribute annotations illegal on non-module declarations for which we do not collect an attribute context.

### CODE REVIEW

File: RubberduckTests/Grammar/VBAParserTests.cs [hunk 1]
```diff
@@ -995,7 +995,51 @@ public void TestNestedVbFormModuleConfigWithProperty()
             AssertTree(parseResult.Item1, parseResult.Item2, "//moduleConfigProperty", matches => matches.Count == 1);
         }
 
-        
+
+        [Test]
+        public void GermanStyleFloatingPointsInFormsPart()
```
Comment (bclothier) [inline RubberduckTests/Grammar/VBAParserTests.cs]: Should we have another test that has both formats in the same form definition to assert that it works for either formats?

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 2]
```diff
@@ -2210,6 +2210,27 @@ End Sub
             }
         }
 
+        [Category("Grammar")]
+        [Category("Resolver")]
+        [Test]
+        public void ObjectPrintExpr_IsReferenceToLocalVariable()
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Do we need another test for the case of 
```
xxx.Print foo, bar; baz : xxx.Print baz, bar; foo
```

It's not clear from the grammar file what happens if there's an instruction separator after a `Print`, which ic a legal thing. See my other comment RE: grammar.

File: Rubberduck.Parsing/Grammar/VBAParser.g4 [hunk 3]
```diff
@@ -258,9 +263,9 @@ lineWidth : expression;
 // and let the resolver handle it.
 debugPrintStmt : debugPrint (whiteSpace outputList)?;
 // We split it up into separate rules so that we have context classes generated that can be used in declarations/references.
-debugPrint : debugModule whiteSpace? DOT whiteSpace? debugPrintSub;
+debugPrint : debugModule whiteSpace? DOT whiteSpace? printMethod;
 debugModule : DEBUG;
-debugPrintSub : PRINT;
+printMethod : PRINT;
```
Comment (bclothier) [inline Rubberduck.Parsing/Grammar/VBAParser.g4]: I can't help but wonder if it should be `PRINT outputList`? 

In fact, I wonder whether we really should have `debugPrint` to begin if the behavior of `Print` is universal regardless whether it's on a `Debug` pseudo object or some other objects.

Comment (MDoerner) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: No, we need a wrapper around the `PRINT` token alone becasue in the resolver everything works off subclasses of `ParserRuleContext` and not `IParseTree`, I guess for historical reasons. Tokens are no `PaserRuleContext`s. Thus, we need a wrapper to allow passing it into a `MemberAccessDefaultBinding` in `DefaultBindingContext` in the reference resolver.

We also need `debugPrint` because we resolve the `Debug` part differently in the `IdentifierReferenceResolver`.

File: RubberduckTests/Grammar/ResolverTests.cs (hunk 2 above)
Comment (MDoerner) [reply RubberduckTests/Grammar/ResolverTests.cs]: That should work just fine as the colon is not a formatting character in the output list. I will add a test nonetheless.

File: RubberduckTests/Grammar/VBAParserTests.cs (hunk 1 above)
Comment (MDoerner) [reply RubberduckTests/Grammar/VBAParserTests.cs]: I see no reason why this should fail, but I will add a test nonetheless.

**Comment by MDoerner** [comment]
I just realized that there is still a part missing to allow VB6's object print statement: inside a form, the object reference is optional.

File: Rubberduck.Parsing/Grammar/VBAParser.g4 (hunk 3 above)
Comment (MDoerner) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: Thinking about it again, I think we can get rid of the special resolution for `Debug`. I will test wether I can do that.

Comment (bclothier) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: I now understand why we have a rule for `PRINT` alone; but we only have this:
```
debugPrintStmt : debugPrint (whiteSpace outputList)?;
```

which probably needs to be redefined into:
```
printStmt: printMethod (whiteSpace outputList)?;
```

to make the `Print` method parse the same way regardless of what object it is on.

Comment (MDoerner) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: No, I just tested; `debugPrintStmt` will disappear entirely.

**Comment by MDoerner** [comment]
Now, the PR also handles the unqualified `Print` and makes `Debug` a standard module.

File: Rubberduck.Parsing/Grammar/VBAParser.g4 [hunk 4]
```diff
@@ -257,8 +257,10 @@ lineWidth : expression;
 
 
 // 5.4.5.8   Print Statement
+//We make the part regarding the file handle optional to support VB6's print statement in forms.
+//It is an invocation of the Print member of the enclosing form, which also takes an output list as argument.
 printMethod : PRINT;
-printStmt : PRINT whiteSpace markedFileNumber whiteSpace? COMMA (whiteSpace? outputList)?;
+printStmt : printMethod (whiteSpace markedFileNumber whiteSpace? COMMA)? (whiteSpace? outputList)?;
```
[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: There is a separate `printStmt` rule.

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 5]
```diff
@@ -2244,14 +2244,49 @@ Sub Test()
...
+        [Category("Grammar")]
+        [Category("Resolver")]
+        [Test]
+        //This form is legal inside VB6 forms and other classes implementing the IVBPrint COM interface.
+        //To simplify the test we use a dummy Sub in the class instead, which cannot be defined in regular VBA.
+        public void UnqualifiedObjectPrintExpr_IsReferencePrintOnContainingModule()
+        {
+            var code = @"
+Sub Test()
+    Dim obj As Object
```
[the remark this answers is not in the document]
Comment (MDoerner) [reply RubberduckTests/Grammar/ResolverTests.cs]: It is pure copy-pasta.

File: Rubberduck.Parsing/Grammar/VBAParser.g4 (hunk 4 above)
[the remark this answers is not in the document]
Comment (retailcoder) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: @bclothier I read this as simply taking a lexer token and making it a parser rule; there is no material change/impact on the parsing itself, just on the resulting parse trees. `PrintStmtContext` still refers to the "print to file" statement, only now with this change it'll have a `printMethod()` member that will yield a `PrintMethodContext` with a `PRINT()` method yielding the token, instead of a `PRINT()` member yielding the token directly.

[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: Since I realize now that this is about the `printStmt`. 
You can easily tell them apart by the presence of `markedFileNumber`.

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 6]
```diff
@@ -6713,5 +6711,79 @@ End Function
...
+        {
+            var classCode = @"
+Public Function Foo(index As Variant) As Class1
+    Assert
+End Function
+";
+
+            var moduleCode = $@"
+Private Function Test() As Variant
+    Assert
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Does it matter that the `Assert` is undeclared for the test?

Comment (MDoerner) [reply RubberduckTests/Grammar/ResolverTests.cs]: That is intentional, Otherwise, it would resolve to the more local declaration in favor of `Debug.Assert`, which we place in the VBA library.

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 7]
```diff
@@ -6785,5 +6784,79 @@ End Function
...
+                .ProjectBuilder("TestProject", ProjectProtection.Unprotected)
+                .AddComponent("Class1", ComponentType.ClassModule, classCode)
+                .AddComponent("Module1", ComponentType.StandardModule, moduleCode)
+                .AddReference("VBA", MockVbeBuilder.LibraryPathVBA, 4, 2, true)
+                .AddProjectToVbeBuilder()
+                .Build();
+
+            using (var state = Resolve(vbe.Object))
+            {
+                var debugAssertDeclaration = state.DeclarationFinder
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Nitpick: this probably should be renamed as `debugPrintDeclaration`

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 8]
```diff
@@ -6785,5 +6784,79 @@ End Function
...
+                    .BuiltInDeclarations(DeclarationType.Procedure)
+                    .Single(declaration => declaration.IdentifierName.Equals("Print")
+                                           && declaration.QualifiedModuleName.ComponentName.Equals("Debug"));
+                var debugAssertReferences = debugAssertDeclaration.References;
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Ditto

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 9]
```diff
@@ -6785,5 +6784,79 @@ End Function
...
+                .ProjectBuilder("TestProject", ProjectProtection.Unprotected)
+                .AddComponent("Class1", ComponentType.ClassModule, classCode)
+                .AddComponent("Module1", ComponentType.StandardModule, moduleCode)
+                .AddReference("VBA", MockVbeBuilder.LibraryPathVBA, 4, 2, true)
+                .AddProjectToVbeBuilder()
+                .Build();
+
+            using (var state = Resolve(vbe.Object))
+            {
+                var debugAssertDeclaration = state.DeclarationFinder
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Ditto

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 10]
```diff
@@ -6785,5 +6784,79 @@ End Function
...
+                    .BuiltInDeclarations(DeclarationType.Procedure)
+                    .Single(declaration => declaration.IdentifierName.Equals("Print")
+                                           && declaration.QualifiedModuleName.ComponentName.Equals("Debug"));
+                var debugAssertReferences = debugAssertDeclaration.References;
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Ditto

File: RubberduckTests/Grammar/VBAParserTests.cs [hunk 11]
```diff
@@ -2614,7 +2614,7 @@ Sub Test()
     Debug.Print 1,
 End Sub";
             var parseResult = Parse(code);
-            AssertTree(parseResult.Item1, parseResult.Item2, "//debugPrintStmt/outputList");
+            AssertTree(parseResult.Item1, parseResult.Item2, "//lExpression/outputList");
```
[the remark this answers is not in the document]
Comment (MDoerner) [reply RubberduckTests/Grammar/VBAParserTests.cs]: `printMethod` looks for the `Print` part. This looks for the `outputList` child of the `objectPrintExpr`. Since the setup does not allow to evaluate whether a child of a named alternative is present, `lExpression` is used for the `objPrintExpr` part.
