### PR TITLE
Revert the attempt to avoid an AV

### LINKED ISSUE #5722: "This action will reset your project" on parse
**Rubberduck version information**
Version 2.5.1.5735
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.13801.20360
Host Executable: MSACCESS.EXE

**Description**
Starting in Version 2.5.1.5735+ I am seeing the "This action will reset your project" popup on parse with one of my projects. This occurs on every parse. I can do it back to back with no running code between. I can open the project file using SHIFT to avoid running any code. When I open it this way I begin getting the message on the second parse and every subsequent parse.

**To Reproduce**
1. Open complex MS-Access project
2. Open VBE
3. Click "Ready" in the RD toolbar to parse

**Expected behavior**
This doesn't happen on Version v2.5.1.5731 or before.

**Screenshots**
image

**Logfile**
```
2021-04-06 14:59:13.0926;WARN-2.5.1.5735;Rubberduck.CodeAnalysis.Inspections.Logistics.Inspector;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Common.StringExtensions.Capitalize(String input) in C:\projects\rubberduck\Rubberduck.InternalApi\Common\StringExtensions.cs:line 13
   at Rubberduck.CodeAnalysis.Inspections.Concrete.ImplementedInterfaceMemberInspection.ResultDescription(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\ImplementedInterfaceMemberInspection.cs:line 75
   at Rubberduck.CodeAnalysis.Inspections.Abstract.DeclarationInspectionBase.InspectionResult(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\DeclarationInspectionBase.cs:line 38
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.DeclarationInspectionBaseBase.<>c__DisplayClass4_0.<DoGetInspectionResults>b__1(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\DeclarationInspectionBaseBase.cs:line 37
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 82
   at Rubberduck.CodeAnalysis.Inspections.Logistics.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Logistics\Inspector.cs:line 175;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Common.StringExtensions.Capitalize(String input) in C:\projects\rubberduck\Rubberduck.InternalApi\Common\StringExtensions.cs:line 13
   at Rubberduck.CodeAnalysis.Inspections.Concrete.ImplementedInterfaceMemberInspection.ResultDescription(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\ImplementedInterfaceMemberInspection.cs:line 75
   at Rubberduck.CodeAnalysis.Inspections.Abstract.DeclarationInspectionBase.InspectionResult(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\DeclarationInspectionBase.cs:line 38
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.DeclarationInspectionBaseBase.<>c__DisplayClass4_0.<DoGetInspectionResults>b__1(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\DeclarationInspectionBaseBase.cs:line 37
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 82
2021-04-06 15:06:08.4096;WARN-2.5.1.5735;Rubberduck.CodeAnalysis.Inspections.Logistics.Inspector;System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Concrete.AssignmentNotUsedInspection.FindUnusedAssignmentNodes(INode node, Declaration localVariable, IEnumerable`1 allAssignmentsAndReferences) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\AssignmentNotUsedInspection.cs:line 133
   at Rubberduck.CodeAnalysis.Inspections.Concrete.AssignmentNotUsedInspection.FindUnusedAssignmentReferences(Declaration localVariable, Walker walker) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\AssignmentNotUsedInspection.cs:line 112
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.IdentifierReferenceInspectionBase.<>c__DisplayClass4_0.<DoGetInspectionResults>b__1(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\IdentifierReferenceInspectionBase.cs:line 26
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 82
   at Rubberduck.CodeAnalysis.Inspections.Logistics.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Logistics\Inspector.cs:line 175;System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Concrete.AssignmentNotUsedInspection.FindUnusedAssignmentNodes(INode node, Declaration localVariable, IEnumerable`1 allAssignmentsAndReferences) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\AssignmentNotUsedInspection.cs:line 133
   at Rubberduck.CodeAnalysis.Inspections.Concrete.AssignmentNotUsedInspection.FindUnusedAssignmentReferences(Declaration localVariable, Walker walker) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\AssignmentNotUsedInspection.cs:line 112
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.IdentifierReferenceInspectionBase.<>c__DisplayClass4_0.<DoGetInspectionResults>b__1(Declaration declaration) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\IdentifierReferenceInspectionBase.cs:line 26
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.CodeAnalysis.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 82
   at Rubberduck.CodeAnalysis.Inspections.Logistics.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Logistics\Inspector.cs:line 175
```

**Additional context**
This only happens with some project files

### PR DESCRIPTION
**Pull request by bclothier**
Closes #5722

Reverts the change from #5675 -- left a inline comment explaining the situation for future attempts.

### CODE REVIEW

File: Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeLibVBEExtensions.cs [hunk 1]
```diff
@@ -89,23 +89,24 @@ public bool CompileProject()
...
-                {
-                    Logger.Info(ex, $"Cannot compile the VBA project '{_name}' because there may be a potential access violation.");
-                    return false;
-                }
+                // FIXME: Prevent an access violation when calling CompileProject(). A easy way to reproduce
+                // this AV is to parse an Access project, then do a Compact & Repair, then try to shut down
+                // Access. There was an attempt to avoid the AV by calling PlaceHolder3 which did seem to prevent
+                // the AV but somehow alters the VBA project in such way that _sometimes_ the user is shown a message
+                // that the project has changed and whether the user wants to proceeds. That is a slightly worse fix
+                // than the AV prevention, so we had to remove the fix. Reference:
```
Comment (retailcoder) [inline Rubberduck.VBEEditor/ComManagement/TypeLibs/TypeLibVBEExtensions.cs:97]: Whenever I repro'd this in Excel, I was getting an "Unspecified error" msgbox multiple times on initial load (before the RD splash comes up), and then multiple times again whenever I tried doing anything in the project; the only "fix" I could find was to destroy the broken file and load a not-corrupted version of the host document... which is pretty bad.
