### PR TITLE
Excel crashes with RubberDuck when closing an Excel workbook

### LINKED ISSUE #3415: Excel crashes with RubberDuck when closing an Excel workbook
The whole of Excel crashes when closing down a workbook when RubberDuck is loaded. Using latest version (v2.1.0.2289-pre)

Is there a log stored anywhere? And if so where?

### PR DESCRIPTION
**Pull request by mansellan**
ref. #3415

### CODE REVIEW

File: Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs [hunk 1]
```diff
@@ -174,7 +177,7 @@ private static void AttachEvents(VB.VBComponents components)
         {
             lock (Locker)
             {
-                if (_components == null)
+                if (_components == null && components != null)
```
Comment (retailcoder) [inline Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs]: Note: this works, but only because the `SafeComWrapper` base class overrides equality/inequality operators.

File: Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs [hunk 2]
```diff
@@ -101,7 +101,7 @@ public void ImportSourceFile(string path)
         {
             var ext = Path.GetExtension(path);
             var name = Path.GetFileNameWithoutExtension(path);
-            if (!File.Exists(path))
+            if (!File.Exists(path) || this[name] == null)
```
Comment (retailcoder) [inline Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs]: How about just doing `if (IsWrappingNullReference) { return; }` first thing instead?

File: Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs [hunk 3]
```diff
@@ -152,6 +152,9 @@ public void ImportSourceFile(string path)
 
         public void RemoveSafely(IVBComponent component)
         {
+            if (component == null)
+                { return; }
```
Comment (retailcoder) [inline Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs]: Again, this leverages the `==` operator override; works but `if (component.IsWrappingNullReference) { return; }` would be better I think.

Comment (retailcoder) [reply Rubberduck.VBEEditor/SafeComWrappers/VBA/VBComponents.cs]: Please either remove the extraneous indentation, or bring `{ return; }` on the same line as the `if`.
