### PR TITLE
Refactor and fix MemberNotOnInterfaceInspection, add ApplicationWorksheetFunctionInspection.

### LINKED ISSUE #2238: Inspection for unrecognized Excel.Application methods and/or members
Usage of the `Excel.Application` object is seemingly loosely compiled, presumably to accommodate things like bypassing the `WorksheetFunction` object with statements like `Application.Pi`. See #2236 

The VBA compiler in Excel seems to ignore usage of unrecognized members, so it doesn't make a distinction between a valid member such as `Application.Name`, a worksheet function member such as `Application.Pi`, or non-existent members such as `Application.ILikeTheSmellOfFooBarInTheMorning`.

The project compiles, but a runtime error 438 occurs when executing the line.

Once Rubberduck is aware of the pseudo-worksheet functions ( #2237 ), RD should be able to identify the non-existent members and warn the user at design time.

This behavior seems to be unique to `Excel.Application`. For example, `Word.Application` enforces compilation, and compilation errors occur if a method/member isn't recognized.

### PR DESCRIPTION
**Pull request by comintern**
Closes #2238

### CODE REVIEW

File: Rubberduck.VBEEditor/Application/IHostApplication.cs [hunk 1]
```diff
@@ -5,10 +5,11 @@ namespace Rubberduck.VBEditor.Application
...
     {
         /// <summary>
-        /// Runs VBA procedure specified by name.
+        /// Runs VBA procedure specified by name. WARNING: The parameter is declared as dynamic to prevent circular referencing.
+        /// This should ONLY be passed a Declaration object.
         /// </summary>
-        /// <param name="qualifiedMemberName">The method to be executed.</param>
-        void Run(QualifiedMemberName qualifiedMemberName);
+        /// <param name="declaration">The Declaration object for the method to be executed.</param>
+        void Run(dynamic declaration);
```
Comment (comintern) [inline Rubberduck.VBEEditor/Application/IHostApplication.cs]: The overhead for this should be minimal compared with actually running the unit tests.  Unit testing is the only place ProjectDisplayName is used, and then only in some hosts.  Changing this to dynamic allows only resolving this (which is horrendously expensive and a UI disaster) once per project and once per parse at a maximum, never if unit tests aren't run in an effected host.
