### PR TITLE
SetAssignmentWithIncompatibleObjectTypeInspection

### LINKED ISSUE #3937: Early-bound named parameters not resolved?
We correctly resolve `Excel.Range.Cells` calls, for example:

    foo = currentRow.Range.Cells(12).Value

However given named parameters:

    foo = currentRow.Range.Cells(ColumnIndex:=12).Value

Selecting the `ColumnIndex` identifier doesn't update the status bar with the expected `ColumnIndex (parameter: Long)`, which makes me wonder if we resolve named parameters.

We *are* resolving user code's named parameters (although it doesn't seem to work for recursive calls).

This isn't a high-priority bug at all, since it doesn't affect inspections or refactorings (perhaps it's exactly why we didn't bother with resolving those), however it does affect the context-sensitive reference count in the status bar, making it feel as though something isn't working as it should.

I haven't looked at the source, but it seems to me this could be a fairly easy thing to fix - likely the resolver is simply deliberately working off user declarations when resolving named parameters; if that's the case then the fix is just a matter of making it include the referenced declarations too.

### LINKED ISSUE #4981: Interface casting should be statically checked
**What**

Given the following code:
```vb
Dim x As Something
Dim y As IOtherThing

Set x = New Something
Set y = x 'Uh oh, SomeThing doesn't implement IOtherThing
```

It will compile but blow up with a runtime error. In this context, the `Something` is a VBA class, and there is absolutely no reason why we can't statically infer whether the cast is valid or not, since a class would have to have a `Implements IOtherThing` in its definition.

**Why**

As codebase grows and number of interfaces increase, the loose checking by VBA compiler becomes intolerant and we really really do not want runtime errors. Rubberduck should be smarter than VBA compiler and yell at us that we did something boneheaded so that we can addressed.

**Example**
This code should trigger the inspection:

`IOtherThing` Interface
```vb
Public Sub DoOtherThing()
End Sub
```

`SomeThing` class module
```vb
'Not implementing IOtherThing because it's... not "other" but "some...

Public Sub DoSomething()
End Sub
```

Test code:
```vb
Public Sub DoIt()
  Dim s As SomeThing
  Dim i As IOtherThing

  Set s = New SomeThing
  Set i = s 'runtime error
End Sub
```

---

**QuickFixes**

Not sure a Quickfix can be suggested other than removing the invalid cast (which may cause other problems). I would be fine with having no quickfixes, since this is usually something the programmer needs to correct. We could also consider having a quickfix to slap on the missing interface, though I would rather do this manually.

1. **Add missing interface**

    Example code, after quickfix is applied:

    `Something` Class
    ```vb
    Implements IOtherThing

    Public Sub DoSomething()
    End Sub

    Private Sub IOtherThing_DoOtherThing()
    End Sub
    ```

---

**Resources**
Each inspection needs a number of resource strings - please provide a suggestion here:

 - **InspectionNames**: `VBA Class does not implement the interface`
 - **InspectionInfo**: `The statement attempts to cast a VBA class to a VBA interface but the VBA class does not contain the necessary 'Implements'` statement implementing this interface. Thus, this will fail with a runtime error. VBA compiler will not check the validity of the cast.
 - **InspectionResults**: `Cannot cast {0} into {1}`; `{0}` = class name, `{1}` = interface name

### LINKED ISSUE #5069: What does Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext' mean?
Thanks in advance!

**Rubberduck version information**
    Rubberduck version [2.4.1.4627]
    Operating System: [Microsoft Windows NT 10.0.17763.0 x64]
    Host Product: [Microsoft Office x64]
    Host Version: [16.0.11328.20368]
    Host Executable: [EXCEL.EXE]

**Description**
I created a macro-enabled spreadsheet with simple buttons that run particular macros when clicked on. I am trying to add unit tests to these functions I wrote. To do so, I added one function at a time to a new spreadsheet and wrote tests for each function I added. However, when I added a particular function, `Function getDataFromFile(parFileName As String, parDelimiter As String, Optional parExcludeCharacter As String = "") As Variant` within the `AnalysisMethods` module, I got an `InvalidCastException`. Now I can't run any of my old tests anymore. Any help to debug this would be much appreciated! 

In other words, **what does Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext' mean?**

**To Reproduce**
1. Open up the Test Explorer
2. Click the refresh button
3. Right-click on any test and select Run single test 
4. Open log and look for ERROR

**Expected behavior**
I was hoping that the old unit tests I wrote could execute.

**Logfile**
```
2019-07-24 20:41:45.6145;ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Exception thrown resolving 'VBAProject.AnalysisMethods' (thread 5).;System.InvalidCastException: Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext'.
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(RedimStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 261
   at Rubberduck.Parsing.Grammar.VBAParser.RedimStmtContext.EnterRule(IParseTreeListener listener) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 11082
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase.ResolveReferences(DeclarationFinder finder, QualifiedModuleName module, IParseTree tree, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ReferenceManagement\ReferenceResolveRunnerBase.cs:line 251
```

**Additional context**
Here is the function that caused the problem. (I can't seem to attach the spreadsheet.)
```
'Helper function for copyDataFromCsvFileToSheet
Function getDataFromFile(parFileName As String, parDelimiter As String, Optional parExcludeCharacter As String = "") As Variant
'parFileName is the delimited file (csv, txt ...)
'parDelimiter is the separator, e.g. semicolon.
'The function returns an empty array, if the file
'is empty or cannot be opened.
'Number of columns is based on the line with most
'columns and not the first line.
'parExcludeCharacter: Some csv files have strings in
'quotations marks ("ABC"), and if parExcludeCharacter = """"
'quotation marks are removed.

Dim locLinesList() As Variant 'Array
Dim locData As Variant        'Array
Dim i As Long                 'Counter
Dim j As Long                 'Counter
Dim locNumRows As Long        'Nb of rows
Dim locNumCols As Long        'Nb of columns
Dim fso As Variant            'File system object
Dim ts As Variant             'File variable
Const REDIM_STEP = 10000      'Constant

'If this fails you need to reference Microsoft Scripting Runtime.
'You select this in "Tools" (VBA editor menu).
Set fso = CreateObject("Scripting.FileSystemObject")

On Error GoTo error_open_file
'Sets ts = the file
Set ts = fso.OpenTextFile(parFileName)
On Error GoTo unhandled_error

'Initialise the array
ReDim locLinesList(1 To 1) As Variant
i = 0
'Loops through the file, counts the number of lines (rows)
'and finds the highest number of columns.
Do While Not ts.AtEndOfStream
  'If the row number Mod 10000 = 0
  'we redimension the array.
  If i Mod REDIM_STEP = 0 Then
    ReDim Preserve locLinesList _
    (1 To UBound(locLinesList, 1) + REDIM_STEP) As Variant
  End If
  locLinesList(i + 1) = Split(ts.ReadLine, parDelimiter)
  j = UBound(locLinesList(i + 1), 1) 'Nb of columns in present row
  'If the number of columns is then highest so far.
  'the new number is saved.
  If locNumCols < j Then locNumCols = j
  i = i + 1
Loop

ts.Close 'Close file

locNumRows = i

'If number of rows is zero
If locNumRows = 0 Then Exit Function

ReDim locData(1 To locNumRows, 1 To locNumCols + 1) As Variant

'Copies the file values into an array.
'If parExcludeCharacter has a value,
'the characters are removed.
If parExcludeCharacter <> "" Then
  For i = 1 To locNumRows
    For j = 0 To UBound(locLinesList(i), 1)
      If Left(locLinesList(i)(j), 1) = parExcludeCharacter Then
        If Right(locLinesList(i)(j), 1) = parExcludeCharacter Then
          locLinesList(i)(j) = _
          Mid(locLinesList(i)(j), 2, Len(locLinesList(i)(j)) - 2)
        Else
          locLinesList(i)(j) = _
          Right(locLinesList(i)(j), Len(locLinesList(i)(j)) - 1)
        End If
      ElseIf Right(locLinesList(i)(j), 1) = parExcludeCharacter Then
        locLinesList(i)(j) = _
        Left(locLinesList(i)(j), Len(locLinesList(i)(j)) - 1)
      End If
      locData(i, j + 1) = locLinesList(i)(j)
    Next j
  Next i
Else
  For i = 1 To locNumRows
    For j = 0 To UBound(locLinesList(i), 1)
      locData(i, j + 1) = locLinesList(i)(j)
    Next j
  Next i
End If

getDataFromFile = locData

Exit Function

error_open_file:  'Returns empty Variant
unhandled_error:  'Returns empty Variant

End Function
```

### LINKED ISSUE #5071: @Description Annonation
**Rubberduck version information**
Version 2.4.1.4627
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11727.20244
Host Executable: MSACCESS.EXE

**Description**
An issue with Rubberduck fixing, adding a missing attribute, where space is before the opening bracket.  After RD fixing the annotation, it produces a compile error due to the attribute being displayed in the code pane. 

Eg. After RD fixing the attribute:
'@Description ("Function description.")
Public Function MyFunction() As String
Attribute MyFunction.VB_Description = ("Function description.")
End Function

Exporting the class it appears ok.  When I restart the MS Access Application the attribute shows up still in the code pane. 

If I manually remove the offending:
Attribute MyFunction.VB_Description = ("Function description.")
Then export it the description attribute has been removed.

**To Reproduce**
'@Description  ("Function description.")

**Expected behavior**
Description annotation to be added as when there is no space between the '@Description 
and the opening bracket. 

**Screenshots**
Rubberduck Issue Fixing Add Description Annotation

### PR DESCRIPTION
**Pull request by MDoerner**
Closes #4981
Closes #5069
Closes #5071
Closes #3937

This PR already covers the scope layed out in the first issue above, i.e. it curently supports variable assignments on the RHS. However, I think that this is not too useful yet. So, I plan to extend the scope to new expressions, index expressions and member access expressions on the RHS.

### CODE REVIEW

File: Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+        ///
+        ///     Set cls = New Class1
+        ///     Set intrfc = cls 
+        /// End Sub
+        /// ]]>
+        /// </example>
+        public SetAssignmentWithIncompatibleObjectTypeInspection(RubberduckParserState state)
+            : base(state)
+        {
+            _declarationFinderProvider = state;
```
Comment (bclothier) [inline Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs]: Shouldn't the default be set to error, rather than warning, given that any hits the inspection returns is most definitely a bug in the code?

File: RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs [hunk 2]
```diff
@@ -0,0 +1,487 @@
...
+";
+
+            const string consumerModule =
+                @"
+Private Sub TestIt()
+    Dim intrfc As Interface1
+    Dim cls As Class1
+
+    Set intrfc = new Class2
+    Set cls = intrfc
```
Comment (bclothier) [inline RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs]: I think this is best handled by a separate inspection to warn about suspicious casts, since we should be able to use code path analysis to determine that it came from `new Class2` originally. A separate inspection also means a separate severity, which would be lower since it's not as obvious that the code is flawed.

File: Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs (hunk 1 above)
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs]: I guess, error makes sense.

However, note that there are situations in which the assignment will be legal. If you assign an object with one declared interface to a variable with another declared interface, the assignment is legal if the underlying object happens to implement both interfaces.

File: RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs (hunk 2 above)
Comment (MDoerner) [reply RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs]: Note that we cannot always determine all illegal downcasts. This situation is rather artifical. I would usually suspect downcasts  to be performed on objects being passed into a method through parameters whose declared type is the interface.

Should we warn about all downcasts? (Not part of this PR)

File: Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs (hunk 1 above)
Comment (bclothier) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs]: That's why as alluded in the other comment below, such ambiguous cases would be a separate inspection with lower severity. The error inspection should only take cases where it is very clear that the code cannot run under any circumstances.

File: RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs (hunk 2 above)
Comment (retailcoder) [reply RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs]: Wouldn't that literally be the expectation in a code base that's written against interfaces? e.g. a factory method that creates a `New Something` but returns an `ISomething`?

File: Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs (hunk 1 above)
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs]: I would like to differ. Only covering the cases for which we can prove that a runtime error will be raised will heavily limit the cases this inspection reports as an issue and make the implementation much more complicated because it would involve code path analysis. 

I think the VBE specifically does not check the declared object type beacuse under most circumstances it cannot know for certain which interfaces will be implemented on the object used in the assignment. 

It is always possible to split assignments into multiple steps to only use direct downcasts and upcasts.

File: RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs (hunk 2 above)
Comment (MDoerner) [reply RubberduckTests/Inspections/SetAssignmentWithIncompatibleObjectTypeInspectionTests.cs]: Why would a downcast be expected when writing against interfaces?

Given that `Something` implements `ISomething`,
```vba
Private Function Upcast(cls As Something) As ISomething
    Set Upcast = cls
End Function
```
is an upcast and
```vba
Private Function Downcast(cls As ISomething) As Something
    Set Downcast = cls
End Function
```
a downcast.

**Comment by MDoerner** [comment]
This PR is largely finished now. It introduces a `SetTypeResolver` able to provide the set type name and declaration for all expressions for which these can be reolved at compile time. This is used to supply the set type name for the inspection in order to compare it with the LHS of the Set assignment.

The current implementation uses identifier references to determine the Set type. This has the advandage over putting the information on the contextx themselves that no further cash invalidation is required.

I still plan to do some clean up in `IndexDefaultbinding` and `BondExpressionVisitor` around the resolution of index expressions. However, I would already apprechieate any feedback I could get, especially on the Set resolver.

**Comment by MDoerner** [comment]
I basically rewrote the resolution of index expressions in the last commits to simplify things in the resolver. This includes attaching references to array accesses with a new flag `IsArrayAccess`. I also added the new flag `IsDefaultMemberAccess` to better identify these accesses. These are now also part of the `IndexExpression`, which was the basic change alllowing for a cleaner handling of these situations.

I do not plan to add anything further to this PR excpt in response to review comments.

File: Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs [hunk 3]
```diff
@@ -0,0 +1,209 @@
...
+                return CreateFailedExpression(_lExpression);
+            }
+
+            var lDeclaration = _lExpression.ReferencedDeclaration;
+
+            if (_lExpression.Classification == ExpressionClassification.Unbound)
+            {
+                /*
+                     <l-expression> is classified as an unbound member. In this case, the dictionary access expression  
+                    is classified as an unbound member with a declared type of Variant, referencing <l-expression> with no member name.
```
Comment (bclothier) [inline Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs]: If that is a quote from the specs, it might be good to include the reference. I see there are a number of other similar comments -- the suggestions applies to them all.

File: Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs [hunk 4]
```diff
@@ -123,178 +117,210 @@ private IBoundExpression CreateFailedExpression(IBoundExpression lExpression)
...
+
+            if (defaultMember.DeclarationType == DeclarationType.Procedure)
+            {
+                return ExpressionClassification.Subroutine;
+            }
+
+            return ExpressionClassification.Function;
+        }
+
+        private static bool IsPropertyGetLetFunctionProcedure(Declaration declaration)
```
Comment (bclothier) [inline Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs]: I note that this (and the following functions) seems to be also in the DictionaryAccessDefaultBinding. Can we DRY those helper functions?

File: Rubberduck.Parsing/Grammar/VBAParser.g4 [hunk 5]
```diff
@@ -647,6 +647,7 @@ visibility : PRIVATE | PUBLIC | FRIEND | GLOBAL;
 // 5.6 Expressions
 expression :
     // Literal Expression has to come before lExpression, otherwise it'll be classified as simple name expression instead.
+	//The same holds for Built-in Type Expression.
```
Comment (bclothier) [inline Rubberduck.Parsing/Grammar/VBAParser.g4]: Tabs/spaces?

File: Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs [hunk 6]
```diff
@@ -0,0 +1,268 @@
...
+using Rubberduck.Parsing.Symbols;
+using Rubberduck.Parsing.VBA;
+using Rubberduck.Parsing.VBA.DeclarationCaching;
+using Rubberduck.VBEditor;
+
+namespace Rubberduck.Parsing.TypeResolvers
+{
+    public class SetTypeResolver :  ISetTypeResolver
+    {
+        public const string NotAnObject = "NotAnObject";
```
Comment (bclothier) [inline Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs]: Though it's very unlikely we'll encounter a string `NotAnObject` somewhere, one might want to consider adding certain characters which would be ordinary an illegal identifier name to make it even unlikely.

File: Rubberduck.VBEEditor/Selection.cs [hunk 7]
```diff
@@ -141,16 +144,30 @@ public override string ToString()
 
         public static bool operator >(Selection selection1, Selection selection2)
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Selection.cs]: Just an idea - maybe add an xml docs to the operator. That might light up in intellisense and help bring the attention to somehow strange implementation?

File: RubberduckTests/ExpressionResolving/SetTypeResolverTests.cs [hunk 8]
```diff
@@ -0,0 +1,1303 @@
...
+        [Category("ExpressionResolver")]
+        [TestCase("Object", "Object")]
+        [TestCase("[Object]", "Object")]
+        [TestCase("Variant", "Variant")]
+        [TestCase("[Variant]", "Variant")]
+        [TestCase("Any", "Any")]
+        [TestCase("[Any]", "Any")]
+        [TestCase("Long", SetTypeResolver.NotAnObject)]
+        [TestCase("[Long]", SetTypeResolver.NotAnObject)]
+        public void BuiltInTypeExpression_SetTypeNameTests(string builtInType, string expectedSetTypeName)
```
Comment (bclothier) [inline RubberduckTests/ExpressionResolving/SetTypeResolverTests.cs]: That is an excellent test. 👍 Really highlights the WTF-ness of VBA.

File: RubberduckTests/Grammar/ResolverTests.cs [hunk 9]
```diff
@@ -3002,5 +3012,289 @@ End Sub
...
+                var module = state.DeclarationFinder.AllModules.First(qmn => qmn.ComponentName == "Module1");
+                var qualifiedSelection = new QualifiedSelection(module, selection);
+                var reference = state.DeclarationFinder.IdentifierReferences(qualifiedSelection).First();
+                var referencedDeclaration = reference.Declaration;
+
+                var expectedReferencedDeclarationName = "Class1.Foo";
+                var actualReferencedDeclarationName = $"{referencedDeclaration.ComponentName}.{referencedDeclaration.IdentifierName}";
+
+                Assert.AreEqual(expectedReferencedDeclarationName, actualReferencedDeclarationName);
+                Assert.IsTrue(reference.IsDefaultMemberAccess);
```
Comment (bclothier) [inline RubberduckTests/Grammar/ResolverTests.cs]: Do we need to also test the intermediate access, too, to prove that intermediate declarations are not mutated when resolving chained access?

File: RubberduckTests/Refactoring/MoveCloserToUsageTests.cs [hunk 10]
```diff
@@ -767,7 +767,6 @@ public void MoveCloserToUsageRefactoring_TargetInDifferentNonStandardModule()
         [Test]
         [Category("Refactorings")]
         [Category("Move Closer")]
-        [Ignore("For some reason the reference is not recognized by the resolver in this test.")]
```
Comment (bclothier) [inline RubberduckTests/Refactoring/MoveCloserToUsageTests.cs]: 🎉 Nice to see less ignored tests

File: Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs (hunk 6 above)
Comment (Vogel612) [reply Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs]: from an earlier chat conversation around that I recall this string being as good as an illegal identifier, because the types are qualified with the project name and there is no built-in type with that name

File: Rubberduck.CodeAnalysis/Inspections/Concrete/AssignedByValParameterInspection.cs [hunk 11]
```diff
@@ -48,12 +48,41 @@ protected override IEnumerable<IInspectionResult> DoGetInspectionResults()
...
+            var declaration = reference.Declaration;
+            if (declaration == null)
+            {
+                return false;
+            }
+
+            if (declaration.IsObject)
+            {
+                //This can only be legal with a default member access.
+                return false;
```
[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/AssignedByValParameterInspection.cs]: This will probably have to stay like this, even if we resolve implicit default member calls, since we cannot get all. (If the type is `Object`, we cannot know the default member.)

Still, I will add a todo in case we can get rid of the assignment flags.

File: Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs (hunk 3 above)
Comment (MDoerner) [reply Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs]: I would rather remove the quote from the index expression section than find some link for it. I only copied it over from the `IndexDefaultBinding` where autoboosh inserted all those quotes.

File: Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs (hunk 4 above)
Comment (MDoerner) [reply Rubberduck.Parsing/Binding/Bindings/IndexDefaultBinding.cs]: I would rather not like to DRY this. There is no good place to put these functions as they are of no use to anything else. Moreover, they do not contain any significant logic. The only reason they have been extracted is to make one conditional more readable.

File: Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs (hunk 6 above)
Comment (MDoerner) [reply Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs]: Exactly

File: Rubberduck.Parsing/Grammar/VBAParser.g4 (hunk 5 above)
Comment (MDoerner) [reply Rubberduck.Parsing/Grammar/VBAParser.g4]: Will fix

File: RubberduckTests/Refactoring/MoveCloserToUsageTests.cs (hunk 10 above)
Comment (MDoerner) [reply RubberduckTests/Refactoring/MoveCloserToUsageTests.cs]: I will go through the other ignored tests and see whether more of them work now.

File: RubberduckTests/Grammar/ResolverTests.cs (hunk 9 above)
Comment (MDoerner) [reply RubberduckTests/Grammar/ResolverTests.cs]: What do you mean with _mutated_?

File: Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs (hunk 3 above)
Comment (bclothier) [reply Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs]: I understand that in general we don't want comments in our code but IMPOV, the resolver is quite dense, and also represents an implementation of the specs, so I think it benefits the maintainers to have the citation at the hand when following the logic, especially if we find something wrong with the specification or need to do something different. 

If you'd rather not want the extra effort, that is OK, in which case I'd probably leave the quotes alone.

File: RubberduckTests/Grammar/ResolverTests.cs (hunk 9 above)
Comment (bclothier) [reply RubberduckTests/Grammar/ResolverTests.cs]: I did not see any tests on the declarations for the intermediate access, and we need to ensure that any future changes to the resolver do not inadvertently change how the intermediate declaration is formed which would pass those tests and the tests for the binding on non-chained declarations but produces invalid output simply because it's an intermediate access.

Comment (MDoerner) [reply RubberduckTests/Grammar/ResolverTests.cs]: I will add two more tests, one for the intermediate and one for the final dictionary access on a chain with different default members being called.

Moreover, I will add two similar tests for Ann indexed default member access on a dictionary access.

File: Rubberduck.CodeAnalysis/Inspections/Concrete/AssignedByValParameterInspection.cs (hunk 11 above)
[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/AssignedByValParameterInspection.cs]: Done

File: Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs (hunk 3 above)
Comment (MDoerner) [reply Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs]: I have added links to the spec to the top of the `IndexDefaultBinding` and `DictionaryAccessDefaultBinding`.

File: Rubberduck.VBEEditor/Selection.cs (hunk 7 above)
Comment (MDoerner) [reply Rubberduck.VBEEditor/Selection.cs]: Done

File: RubberduckTests/Grammar/ResolverTests.cs (hunk 9 above)
Comment (MDoerner) [reply RubberduckTests/Grammar/ResolverTests.cs]: I have added these tests and a few more, uncovering a further bug: default member and array accesses on dictionary access expressions were not resolved correctly.

File: RubberduckTests/Refactoring/MoveCloserToUsageTests.cs (hunk 10 above)
Comment (MDoerner) [reply RubberduckTests/Refactoring/MoveCloserToUsageTests.cs]: This has already led to fixing issue #3937.

File: Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs (hunk 1 above)
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs]: The severity is error now.

File: RubberduckTests/Refactoring/MoveCloserToUsageTests.cs (hunk 10 above)
Comment (MDoerner) [reply RubberduckTests/Refactoring/MoveCloserToUsageTests.cs]: I ahev reviewed the remaining ignored test and could unignore a few, mostly fixed in previous PRs.

File: RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs [hunk 12]
```diff
@@ -11,7 +11,6 @@ namespace RubberduckTests.Inspections
     public class ImplicitActiveWorkbookReferenceInspectionTests
     {
         [Test]
-        [Ignore("This was apparently only passing due to the test setup. See #4404")]
```
Comment (bclothier) [inline RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs]: Are we sure we want to unignore this? The comment suggests it is a false positive?

File: RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs [hunk 13]
```diff
@@ -304,9 +304,9 @@ End Enum
 
         // This is a corner case similar to #4037. Previously, Collection's default member was not being generated correctly in
         // when it was loaded by the COM collector (_Collection is missing the default interface flag). After picking up that member
-        // this test fails because it resolves as attempting to assign 'New Colletion' to `Test.DefaultMember`.
+        // this test fails because it resolves as attempting to assign 'New Collection' to `Test.DefaultMember`.
         [Test]
-        [Ignore("Broken by COM collector fix. See comment on test.")]
+        //[Ignore("Broken by COM collector fix. See comment on test.")]
```
Comment (bclothier) [inline RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs]: If it's working, do we really need the comment (both of them) anymore?

File: Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs [hunk 14]
```diff
@@ -0,0 +1,198 @@
...
+        /// Public Sub DoIt()
+        ///     Dim cls As Class1
+        ///     Dim intrfc As IInterface
+        ///
+        ///     Set cls = New Class1
+        ///     Set intrfc = cls 
+        /// End Sub
+        /// ]]>
+        /// </example>
+        /// <example>
```
Comment (retailcoder) [inline Rubberduck.CodeAnalysis/Inspections/Concrete/SetAssignmentWithIncompatibleObjectTypeInspection.cs]:
```suggestion
        /// <example hasResult="false">
```

File: Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs [hunk 15]
```diff
@@ -0,0 +1,218 @@
...
+                && DEFAULT_MEMBER_RECURSION_LIMIT > recursionDepth)
+            {
+                /*
+                    This default member cannot accept any parameters. In this case, the static analysis restarts 
+                    recursively, as if this default member was specified instead for <l-expression> with the 
+                    same <argument-list>.
+                */
+
+                return ResolveRecursiveDefaultMember(defaultMember, defaultMemberClassification, argumentList, expression, recursionDepth);
+            }
```
Comment (retailcoder) [inline Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs]: Great job with the comments there 👍

File: Rubberduck.Parsing/Symbols/IdentifierReference.cs [hunk 16]
```diff
@@ -60,6 +64,10 @@ public class IdentifierReference : IEquatable<IdentifierReference>
 
         public bool IsSetAssignment { get; }
 
+        public bool IsDefaultMemberAccess { get; }
```
Comment (retailcoder) [inline Rubberduck.Parsing/Symbols/IdentifierReference.cs]: Brilliant 👍

File: Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs [hunk 17]
```diff
@@ -0,0 +1,268 @@
...
+            return finder
+                .IdentifierReferences(qualifiedSelection)
+                .FirstOrDefault(reference => reference.IsDefaultMemberAccess)
+                ?.Declaration;
+        }
+        
+        //Please note that the lExpression is the (whitespace) index expression itself and not the lExpression it contains. 
+        private Declaration ResolveIndexExpressionAsArrayAccess(VBAParser.LExpressionContext actualIndexExpr, QualifiedModuleName containingModule, DeclarationFinder finder)
+        {
+            // A n array access references the entire (whitespace)indexExpr.
```
Comment (retailcoder) [inline Rubberduck.Parsing/TypeResolvers/SetTypeResolver.cs]:
```suggestion
            // An array access references the entire (whitespace)indexExpr.
```

File: Rubberduck.Resources/Inspections/InspectionNames.resx [hunk 18]
```diff
@@ -386,6 +386,9 @@
   <data name="ObsoleteWhileWendStatementInspection" xml:space="preserve">
     <value>Use of obsolete 'While...Wend' statement</value>
   </data>
+  <data name="SetAssignmentWithIncompatibleObjectTypeInspection" xml:space="preserve">
+    <value>Set Assignment With Incompatible Object Type</value>
```
Comment (retailcoder) [inline Rubberduck.Resources/Inspections/InspectionNames.resx]:
```suggestion
    <value>Set assignment with incompatible object type</value>
```

File: RubberduckTests/Inspections/AssignedByValParameterInspectionTests.cs [hunk 19]
```diff
@@ -170,6 +170,40 @@ End Sub
...
+        [Test]
+        [Category("Inspections")]
+        public void AssignedByValParameter_NoResultForDefaultMembberAssignment()
+        {
+            var class1 = @"
+Public Property Get Something() As Long
+Attribute Foo.VB_UserMemId = 0
+End Property
+Public Property Let Something(ByVal value As Long)
+Attribute Foo.VB_UserMemId = 0
```
Comment (retailcoder) [inline RubberduckTests/Inspections/AssignedByValParameterInspectionTests.cs]: Not that it makes a difference, but is this legal code? IIUC only one member is allowed to have `VB_UserMemId = 0`... I've always only ever put it on the `Property Get` member.

File: RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs (hunk 12 above)
Comment (retailcoder) [reply RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs]: @bclothier I'm missing something. The test setup puts this code in a standard module, where an unqualified `Worksheets` call is indeed an implicit `ActiveWorkbook` reference. Not sure what's wrong with this test.

Comment (MDoerner) [reply RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs]: It refers to a closed issue.

File: RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs (hunk 13 above)
Comment (MDoerner) [reply RubberduckTests/Inspections/ObjectVariableNotSetInspectionTests.cs]: Oh, I missed go remove the ignore line entirely. Will do that later.

File: RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs (hunk 12 above)
Comment (bclothier) [reply RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs]: @retailcoder Neither can I see what is wrong. The comment only say test setup is flawed but it doesn't say how. I do see that issue was closed but when reviewing [the git blame](https://github.com/rubberduck-vba/Rubberduck/blame/master/RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs), this came from #4425 / #4414, and [was only one line of change](https://github.com/rubberduck-vba/Rubberduck/pull/4425/files#diff-3192feb08266c2ee9c7904879905274c). The referenced issue #4404 (and its related cousin) is indeed closed but so far there has been no changes in the test setup. I would have had expected there to be a change in the test setup to warrant the removal of the attribute. 

Because it's without an explanation, I'm in favor of not ignoring this until we actual have an example of why the test setup is invalid.

Comment (MDoerner) [reply RubberduckTests/Inspections/ImplicitActiveWorkbookReferenceInspectionTests.cs]: The test setup has been fixed in commit f28ed0d1 (use serialized COM projects instead of serialized declarations), which is also the commit that introduced the ignore.

When the issue in the inspection got fixed,, we simply missed to unignore the test.

File: Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs (hunk 15 above)
Comment (MDoerner) [reply Rubberduck.Parsing/Binding/Bindings/DictionaryAccessDefaultBinding.cs]: They are basically copied from `IndexDefaultBinding`, where autoboosh added them. I just modified them to refer to a dictionary access expression instead of an index expression.

File: RubberduckTests/Inspections/AssignedByValParameterInspectionTests.cs (hunk 19 above)
Comment (MDoerner) [reply RubberduckTests/Inspections/AssignedByValParameterInspectionTests.cs]: I have no idea. I guess the VBE would just ignore  one of them.
