### PR TITLE
Refresh Testing (Pun Intended)

### LINKED ISSUE #3738: Rubberduck>UnitTest>Run All Tests doesn't update the grouping headers
Below is what is shown when run through Rubberduck>Unit Test>Run All Tests
rubberduck unittests runalltests

Below the grouping headers update appropriately if from the TestExplorer window Run button
runbutton on testexplorer

### LINKED ISSUE #3879: Smarten up the templates for unit testing
We support both early and late bound testing but what I don't like is that they derive from two different templates and make it hard to flip between the states. (You gonna help me enable my intellisense addiction, mmkay?)

My suggested template is provided below:

What it brings:

1) To change between early/late binding, we change *exactly* only one line -- The `#Const LateBind = ...` and add references accordingly.

2) Only one default template to maintain instead of 2. The setting used for binding when adding a test module would be then used to determine what default value of the `#LateBind` should be. WE always use `CreateObject` regardless of the mode, so we do not need to write `Set Assert = New Rubberduck.AssertClass`. 

3) This can be tied into a project-level compilation constant in case we need to support project-wide switch, rather than per-module. This is achieved with `#Const LateBind = LateBind` (assuming the `LateBind` is defined in the project's conditional compilation arguments). This approach also makes it easy for us to conditionally enable only early binding on a particular test module, rather than for all test modules. 

```
Option Compare Database
Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

#Const LateBind = 0

#If LateBind Then
Private Assert As Object
Private Fakes As Object
#Else
Private Assert As Rubberduck.AssertClass
Private Fakes As Rubberduck.FakesProvider
#End If

'@ModuleInitialize
Public Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
End Sub

'@ModuleCleanup
Public Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Public Sub TestInitialize()
    'this method runs before every test in the module.
End Sub

'@TestCleanup
Public Sub TestCleanup()
    'this method runs after every test in the module.
End Sub
```

### LINKED ISSUE #4220: Localize the names of Test Modules
Test Modules are added with a number-suffixed, English module name like TestModule1, but when adding standard, class and document modules in different locales, the VBE uses a localized name.

We don't rely upon the name to identify test modules, so to be user friendly, we should be using localized names.

see #3879

### LINKED ISSUE #4365: Get UnitTesting internals out of Rubberduck.Core
There's some stuff in Rubberduck.Core that does no longer belong there, but which was too disjoint from #4146 to be pushed into there.

As such this is a follow-up issue to deal with the following more or less gaping issues:

 - IVBEInteraction is used outside of UnitTesting
 - AddTestModule command builds it's own template
 - AddTestMethod and AddTestMethodExpectedError don't call into UnitTesting to determine the next test name

Generally the internal API to Rubberduck should be consistent and cleanly exposed and separated into the Rubberduck.UnitTesting assembly

### LINKED ISSUE #4698: Refresh resets all test statuses
In the latest release (2.3.1.4308) a refresh will reset the status of all of my tests regardless of whether or not they have been affected. I remember this not being an issue with the previous version I used, although I can't remember which version that was. In general it makes writing tests and adding new tests a real chore as you have to either find the test you are working on in the menu and run that, or run every test for every change you make to either your code or your tests.

Ideally I want how it used to work as I remember that working "as expected".

**To reproduce**
1. Make an empty sheet with a test module with one empty test.
2. Run the test
3. Click refresh

_Edit (added the version/host info)_

Version 2.3.1.4308
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11029.20108
Host Executable: EXCEL.EXE

### LINKED ISSUE #4701: Test explorer should support multiple selections
Ref #4968

Selection seems to be single and doesn't allow for multiple selections. I thought that was addressed in a previous PR but it does not look like it's the case. That would be an enhancement and would make `Run Selected` feature more useful

_Originally posted by @bclothier in https://github.com/rubberduck-vba/Rubberduck/issues/4698#issuecomment-453072604_

### LINKED ISSUE #4705: Invalidate test results on an individual basis rather than all results when running tests
Originally from https://github.com/rubberduck-vba/Rubberduck/issues/4698#issue-397357974

> In the latest release (2.3.1.4308) a refresh will reset the status of all of my tests regardless of whether or not they have been affected. I remember this not being an issue with the previous version I used, although I can't remember which version that was. In general it makes writing tests and adding new tests a real chore as you have to either find the test you are working on in the menu and run that, or run every test for every change you make to either your code or your tests.
> 
> Ideally I want how it used to work as I remember that working "as expected".
> 
> **To reproduce**
> 
>     1. Make an empty sheet with a test module with one empty test.
> 
>     2. Run the test
> 
>     3. Click refresh
> 
> 
> _Edit (added the version/host info)_
> 
> Version 2.3.1.4308
> OS: Microsoft Windows NT 10.0.17134.0, x64
> Host Product: Microsoft Office x86
> Host Version: 16.0.11029.20108
> Host Executable: EXCEL.EXE

The idea is that the test explorer should be more smart about invalidating only results for tests that actually got ran. The way it is, it will reset all tests' status, which is different from how most unit testing framework behaves. That would make RD's framework more consistent with say, NUnit or MSTests.

### PR DESCRIPTION
**Pull request by comintern**
This PR addresses several UI and structural concerns with Unit Testing.

screenshot from 2019-02-03 23-08-58

- The toolbar in the Test Explorer was refreshed to more closely match the updated CE and IR windows. This fixes the grouping and closes #3738.
- The Test Explorer is now multi-select capable, with options to run single tests via a context menu or all selected tests via either the context menu or the toolbar drop-down. This closes #4701, #4703, and #4704.
- Reparsing the project will now only reset the status of tests that have not been changed (any changes to the test procedure's source code will invalidate it).  In addition, there is now a button on the toolbar to reset all test statuses.  This closes #4705 and by extension closes #4698.
- All of the non-VB text in the test modules is now localizable, as is the module name. This closes #4220.
- There is a new "dual binding" option for added test modules. Given the upcoming addition of user templates and the redesign of the templating (see below), I'd say that this closes #3879.
- This introduces the `ITestCodeGenerator` interface, which moves all test code generation out of `Rubberduck.Core` and into `Rubberduck.UnitTesting`. 
- The `UnitTestSettings` and `UnitTestConfigProvider` are now in `Rubberduck.UnitTesting` where they belong.  This was necessary because of the dependency relationships between the two assemblies. That means they are no longer tied to the application settings, because well, that requires strong coupling and prevented separation of other more meaningful concerns.  Between this and the above item, this closes #4365.
- Test methods are now generated with a default category, addressing #4702. I may add an option prompt to select the category when a new method is added or put that in the context menu in the Test Explorer, but I'm up in the air about the best way to handle that at this point, so I'll leave it to @bclothier to decide if this PR is sufficient to close that issue.

Tagging this as WIP for now in that I still need to re-write a ton of unit test setup that the refactoring broke.  I also discovered that the test coverage for the view models is _really_ scanty, so I'll be adding more tests as appropriate. There's also still some low-hanging fruit in the open unit test issues that may get rolled into this during that process.

Finally, if #4717 merges first, I'm intending on adding collapse all and expand all buttons on the toolbar for the test groups.

### CODE REVIEW

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGeneratorStatics.cs [hunk 1]
```diff
@@ -0,0 +1,140 @@
+﻿using System;
+using Rubberduck.Resources.UnitTesting;
+
+namespace Rubberduck.UnitTesting.UnitTesting
+{
+    public partial class TestCodeGenerator
```
Comment (bclothier) [inline Rubberduck.UnitTesting/UnitTesting/TestCodeGeneratorStatics.cs]: IMPOV, all of the elements here should be coming from a resource file, not hard-coded within a `.cs` file. (ref #4622 for an example).  While making it implement the template (ref #4549 ) may be out of scope for the PR, it should be easy enough to have a resource file contain all the needed elements, which will then aid any future changes to get it to conform to the template model, and thus make the code less hard-coded. We want to avoid writing code that basically takes a bunch of elements and concatenate/interleave them because if the content changes, the code almost invariably must change, too.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+            if (project == null || project.IsWrappingNullReference)
+            {
+                return;
+            }
+
+            var settings = _settings.Create();
+
+            if (settings.BindingMode == BindingMode.EarlyBinding)
+            {
+                // FIXME: Push the actual adding of TestModules into UnitTesting, which sidesteps VBEInteraction being inaccessble here
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs]: Nope. Missed that one. Will remove.

File: Rubberduck.UnitTesting/UnitTesting/ITestCodeGenerator.cs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+﻿using System.Collections.Generic;
+using Rubberduck.Parsing.Symbols;
+using Rubberduck.VBEditor.SafeComWrappers.Abstract;
+
+namespace Rubberduck.UnitTesting.UnitTesting
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/ITestCodeGenerator.cs]: That was auto-generated when I added the class. `Rubberduck.UnitTesting.CodeGeneration` works for me. Will change.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs [hunk 4]
```diff
@@ -0,0 +1,231 @@
...
+                using (var component = components.Add(ComponentType.StandardModule))
+                using (var module = component.CodeModule)
+                {
+                    component.Name = GetNextTestModuleName(project);
+
+                    // Test modules always have appropriate options so remove any pre-generated code.
+                    if (module.CountOfLines > 0)
+                    {
+                        module.DeleteLines(1, module.CountOfLines);
+                    }
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs]: That deletes all code in the module.  The component is newly added, so the only code it can possibly contain at that point are the auto-generated options from the VBE.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs [hunk 5]
```diff
@@ -0,0 +1,231 @@
...
+        }
+
+        private string GetNewTestModuleCode(IVBComponent component, List<Declaration> stubs)
+        {
+            if (stubs is null || !stubs.Any())
+            {
+                return GetNewTestModuleCode(component);
+            }
+
+            var module = string.Join(Environment.NewLine + Environment.NewLine, new [] { GetBaseTestModule() }.Concat(stubs.Select(GetNewTestStubMethod)));
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs]: Will do. The settings get refreshed at the start of `GetBaseTestModule` if they aren't provided.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs [hunk 6]
```diff
@@ -0,0 +1,231 @@
...
+        private string GetBaseTestModule(UnitTestSettings settings = null)
+        {
+            if (settings is null)
+            {
+                settings = _settings.Create();
+            }
+
+            string declaration;
+            string initialization;
+            var asserts = settings.AssertMode == AssertMode.PermissiveAssert ? "PermissiveAssertClass" : "AssertClass";
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs]: We can't use `nameof` here because the types aren't referenced by `Rubberduck.UnitTesting`. I'll comment it.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs [hunk 7]
```diff
@@ -0,0 +1,231 @@
...
+            }
+
+            return $"{TestMethodBaseName}{index}";
+        }
+
+        private IEnumerable<Declaration> GetDeclarationsToStub(Declaration parentDeclaration)
+        {
+            return _state.DeclarationFinder.Members(parentDeclaration)
+                .Where(d =>
+                            Equals(d.ParentDeclaration, parentDeclaration) && d.Accessibility == Accessibility.Public &&
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs]: Agreed. That change will need to happen when #4658 is addressed.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGeneratorStatics.cs [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+        private static string LateBindingDeclarations =>
+@"    Private Assert As Object
+    Private Fakes As Object";
+
+        private static string EarlyBindingDeclarations =>
+@"    Private Assert As Rubberduck.{0}
+    Private Fakes As Rubberduck.FakesProvider";
+
+        private static string DualBindingDeclarations =>
+$@"#Const {LateBindConstName} = 0
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGeneratorStatics.cs]: The only potential issue that I see with that is that it could potentially leave the project in a state where it couldn't be compiled after adding a test module, and we always do a reparse on a module add. I do need to verify that the RD reference gets added as needed when this template is used though.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGeneratorStatics.cs (hunk 1 above)
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGeneratorStatics.cs]: This has to be done at run-time because the locale can be changed in the settings (this is why they're static properties instead of static fields). The difference between the code generation here and a predefined template is that it makes the localization much easier to maintain.

File: Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestCodeGenerator.cs]: I'm an idiot - this _doesn't_ need to be addressed with #4658 - this is looking for methods to generate test stubs for, _not_ tests.  We're creating the tests in a different module, so they have to be public - otherwise the test stub won't be able to call it.  RD don't have to respect the accessibility, but VBA does...

File: Rubberduck.Core/UI/GridViewSort.cs [hunk 9]
```diff
@@ -1,40 +1,40 @@
-﻿using System.Collections.Generic;
-using System.Linq;
+﻿//using System.Collections.Generic;
```
Comment (bclothier) [inline Rubberduck.Core/UI/GridViewSort.cs]: Did you mean to leave this commented-out file in?

File: Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs [hunk 10]
```diff
@@ -125,13 +86,198 @@ public bool IsBusy
...
+        private static readonly Dictionary<TestOutcome, Color> OutcomeColors = new Dictionary<TestOutcome, Color>
+        {
+            { TestOutcome.Unknown, Colors.DimGray },
+            { TestOutcome.Succeeded, Colors.LimeGreen },
+            { TestOutcome.Inconclusive, Colors.Gold },
+            { TestOutcome.Ignored, Colors.Orange },
+            { TestOutcome.Failed, Colors.Red }
+        };
+
+        private TestOutcome _bestOutcome = TestOutcome.Unknown;
```
Comment (bclothier) [inline Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs]: "Best" implies that if a single test passes with 99 failures, we get green. I'm pretty sure that's not the "best" outcome. Maybe `_worstOutcome`? `_lcdOutcome`?

File: Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs [hunk 11]
```diff
@@ -125,13 +86,198 @@ public bool IsBusy
...
+                return;
+            }
+
+            IsBusy = true;
+
+            try
+            {
+                _testEngine.Run(tests.Select(test => test.Method));
+            }
+            catch (Exception ex)
```
Comment (bclothier) [inline Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs]: Would the cancellation get propagated to here? If so, shouldn't we have a `ThreadAbortException` catch block?

File: Rubberduck.Core/UI/GridViewSort.cs (hunk 9 above)
Comment (comintern) [reply Rubberduck.Core/UI/GridViewSort.cs]: Nope, I commented it out to see if it was used and forgot to remove it.  Will fix.

File: Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs (hunk 10 above)
Comment (comintern) [reply Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs]: Doh! I somehow missed that when the logic flipped.  Will fix.

File: Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs (hunk 11 above)
Comment (comintern) [reply Rubberduck.Core/UI/UnitTesting/TestExplorerModel.cs]: The cancellation won't raise a `ThreadAbortException` - the thought of mixing a task cancellation on the UI thread with our own custom message pumping tossed in the mix made me cringe.  It's handled by a simple state flag that just lets the invoke exit normally. Pumping the messages lets the cancel button call the `RequestCancellation()` method directly on the `TestEngine`. The initial discussion on the issue #3158 was **_way_** overthinking this.

File: Rubberduck.Parsing/UIContext/UiDispatcher.cs [hunk 12]
```diff
@@ -53,16 +41,40 @@ public void Invoke(Action action)
...
+                    NativeMethods.TranslateMessage(ref message);
+                    NativeMethods.DispatchMessage(ref message);
+                }
+
+                handle.Free();
+            }
+
+            if (_contextProvider.UiContext == SynchronizationContext.Current)
+            {
+                PumpMessages();
```
Comment (bclothier) [inline Rubberduck.Parsing/UIContext/UiDispatcher.cs]: FWIW, I tripped over this as at first read, I thought I was reading a recursive method but now I see that it's a local function. I assume you elected for a local so it wouldn't be used anywhere else but this method. Maybe consider moving it to be the very first or the very last thing within the method and provide a comment?

File: Rubberduck.Resources/Settings/UnitTestingPage.resx [hunk 13]
```diff
@@ -129,6 +129,9 @@
   <data name="UnitTestSettings_BindingMode" xml:space="preserve">
     <value>Binding mode:</value>
   </data>
+  <data name="UnitTestSettings_DualBinding" xml:space="preserve">
```
Comment (bclothier) [inline Rubberduck.Resources/Settings/UnitTestingPage.resx]: This might be beyond the scope of the PR but now that we're splitting up the resx files, the prefix seems redundant and probably should be gotten rid of at some point in future.

File: Rubberduck.UnitTesting/CodeGeneration/ITestCodeGenerator.cs [hunk 14]
```diff
@@ -0,0 +1,13 @@
...
+using Rubberduck.VBEditor.SafeComWrappers.Abstract;
+
+namespace Rubberduck.UnitTesting.CodeGeneration
+{
+    public interface ITestCodeGenerator
+    {
+        void AddTestModuleToProject(IVBProject project);
+        void AddTestModuleToProject(IVBProject project, Declaration stubSource);
+        string GetNewTestMethodCode(IVBComponent component);
+        string GetNewTestMethodCodeErrorExpected(IVBComponent component);
```
Comment (bclothier) [inline Rubberduck.UnitTesting/CodeGeneration/ITestCodeGenerator.cs]: FWIW - those 2 methods could be consolidated with a 2nd parameter -- perhaps an enum -- to make it easier to extend the stubs beyond the default & expected error templates.

File: Rubberduck.UnitTesting/UnitTesting/TestEngine.cs [hunk 15]
```diff
@@ -34,16 +34,26 @@ internal class TestEngine : ITestEngine
...
+
+        public IReadOnlyList<TestMethod> LastRunTests => _lastRun;
+
         public bool CanRun => AllowedRunStates.Contains(_state.Status) && _vbe.IsInDesignMode;
-        public bool CanRepeatLastRun => LastRun.Any();
+        public bool CanRepeatLastRun => _lastRun.Any();
         
-        private bool refreshBackoff;
-
+        private bool _refreshBackoff;
```
Comment (bclothier) [inline Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: TBH the name of the variable doesn't make sense - "turn refresh back off" is what I think of. Is that what it means?

File: Rubberduck.UnitTesting/UnitTesting/TestEngine.cs [hunk 16]
```diff
@@ -229,22 +274,26 @@ private void RunWhileSuspended(IEnumerable<TestMethod> tests)
                                     Logger.Trace(trace, "Unexpected COMException when running TestInitialize");
                                     continue;
                                 }
+
+                                _uiDispatcher.FlushMessageQueue();
```
Comment (bclothier) [inline Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: This seems to be the only one place in the `RunWhileSuspended` method where we pump the message but we've handled several other events. Shouldn't we pump before/after those other events?

File: Rubberduck.UnitTesting/UnitTesting/TestResult.cs [hunk 17]
```diff
@@ -2,7 +2,7 @@
 
 namespace Rubberduck.UnitTesting
 {
-    public class TestResult
+    public struct TestResult
```
Comment (bclothier) [inline Rubberduck.UnitTesting/UnitTesting/TestResult.cs]: Why not `readonly struct`?

File: Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs [hunk 18]
```diff
@@ -1,222 +1,280 @@
...
         public RunFailedTestsCommand RunFailedTestsCommand { get; set; }
         public RunSucceededTestsCommand RunPassedTestsCommand { get; set; }
-        public CommandBase RunSelectedTestCommand { get; }
-        public CommandBase RunSelectedCategoryTestsCommand { get; }
+        public CommandBase RunSingleTestCommand { get; }
+        public CommandBase RunSelectedTestsCommand { get; }
+        public CommandBase RunSelectedGroupCommand { get; }
 
+        public CommandBase CancelTestRunCommand { get; }
+        public CommandBase ResetResultsCommand { get; }
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs]: The readonly commands assigned in the ctor are specific to the VM (i.e. use VM assets), whereas the injected commands are used throughout the UI.  We're using the same pattern in the other tool window controls, so I was just going with it.  I can add a comment if you want though.

File: Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs [hunk 19]
```diff
@@ -249,28 +307,6 @@ private void ExecuteCopyResultsCommand(object parameter)
...
-        {
-            if (Model.IsBusy || SelectedItem == null)
-            {
-                return false;
-            }
-
-            return ((TestMethod) SelectedItem).Category.Name != string.Empty;
-        }
-
         //KEEP THIS, AS IT MAKES FOR THE BASIS OF A USEFUL *SUMMARY* REPORT
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs]: On quick inspection, probably both. :-D  TBH, all of the copy to clipboard stuff needs to be abstracted a bit (DRY).  It's on my radar...

File: Rubberduck.Parsing/UIContext/UiDispatcher.cs (hunk 12 above)
Comment (comintern) [reply Rubberduck.Parsing/UIContext/UiDispatcher.cs]: You hit the nail on the head re why it's a local function. I'll move it to the bottom (and comment) - I think you're right about it looking "less like recursion" there.

File: Rubberduck.Resources/Settings/UnitTestingPage.resx (hunk 13 above)
Comment (comintern) [reply Rubberduck.Resources/Settings/UnitTestingPage.resx]: Agreed.  The resx files are generally in bad need of clean-up and rearranging. That's a fairly monumental task in and of itself though. Maybe it needs an issue?

File: Rubberduck.UnitTesting/CodeGeneration/ITestCodeGenerator.cs (hunk 14 above)
Comment (comintern) [reply Rubberduck.UnitTesting/CodeGeneration/ITestCodeGenerator.cs]: I could see that, although a two member enum would strike me as a bit weird.  IIR this was the existing naming (or close), but I think if this were extended an enum might be in order.

File: Rubberduck.Resources/Settings/UnitTestingPage.resx (hunk 13 above)
Comment (bclothier) [reply Rubberduck.Resources/Settings/UnitTestingPage.resx]: [Left a comment](https://github.com/rubberduck-vba/Rubberduck/issues/4541#issuecomment-464053990) on #4541 .

File: Rubberduck.UnitTesting/UnitTesting/TestEngine.cs (hunk 15 above)
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: I must have looked at that a hundred times and and said "huh"? It means "don't refresh from the parser if this flag is set and it's otherwise ready".  Any suggestions? Maybe `_deferRefresh` or `_refreshUnsafe`?

File: Rubberduck.Parsing/UIContext/UiDispatcher.cs (hunk 12 above)
Comment (MDoerner) [reply Rubberduck.Parsing/UIContext/UiDispatcher.cs]: At least, with the new build setup, they seem to auto-generated the appropriate code again.

File: Rubberduck.UnitTesting/UnitTesting/TestEngine.cs (hunk 15 above)
Comment (bclothier) [reply Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: I probably would flip the logic and call it `_reactToParserStates` or more simply (but less descriptively), `_listening`.

File: Rubberduck.UnitTesting/UnitTesting/TestEngine.cs (hunk 16 above)
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: That was intentional.  I'm pumping here to catch a possible cancel button press, and by my read that was the only safe place to do it given the requirements for running the test setup and teardown procedures. The templates are probably safe to cancel in the middle of those, but we run every setup method we find so I'm thinking it's best to treat those as a unit (and not to cancel those steps). The rest of the pumping is done prior to raising status events from the `TestEngine`.  In those instances, we _know_ the apartment boundary is in a good state to pump.

File: Rubberduck.UnitTesting/UnitTesting/TestResult.cs (hunk 17 above)
Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestResult.cs]: Because I let R# do that and the IDE complains that it's a 7.2 feature?  :-P

Will fix - it indeed should be readonly.

File: Rubberduck.UnitTesting/UnitTesting/TestEngine.cs (hunk 16 above)
Comment (bclothier) [reply Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: Then that needs to be put in a comment (xmldoc?). That intention is not apparent from reading the source code alone and we'll need to know that when we modify this in future.

Comment (comintern) [reply Rubberduck.UnitTesting/UnitTesting/TestEngine.cs]: OK, I'll actually comment _all_ uses of `FlushMessageQueue` to be safe. There's already an extensive xmldoc warning on the interface itself about safe usage (you should see the tooltip).

File: Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (bclothier) [reply Rubberduck.Core/UI/UnitTesting/TestExplorerViewModel.cs]: That's what I suspected and reading it again, I'm torn - we would have to choose between grouping the injected delegates and homebrewn delegates versus listing the delegates based on their function/names. Both approaches have their merits so we'll have to pick one or other.
