### PR TITLE
Fixed implicit ByRef inspection quick fix interface impementation bug (#3096)

### LINKED ISSUE #3096: ImplicitByRefParameterInspection interface implementation bug
ImplicitByRefParameterInspection does not fix interface implementation when applying the quick fix to an interface member's parameter. Also, this inspection can become a parse tree inspection.

### PR DESCRIPTION
**Pull request by rkapka**
Closes #3096

Apart from fixing the bug, I have made this inspection an instance of `ParseTreeInspectionBase`. The implementation of the inspection and quick fix is very similar to #3069.

### CODE REVIEW

File: Rubberduck.Inspections/Concrete/ImplicitByRefModifierInspection.cs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+    public sealed class ImplicitByRefModifierInspection : ParseTreeInspectionBase
+    {
+        public ImplicitByRefModifierInspection(RubberduckParserState state)
+            : base(state, CodeInspectionSeverity.Hint)
+        {
+        }
+
+        public override CodeInspectionType InspectionType => CodeInspectionType.CodeQualityIssues;
+
+        public override IInspectionListener Listener { get; } = new ImplicitByRefModifierListener();
```
Comment (retailcoder) [inline Rubberduck.Inspections/Concrete/ImplicitByRefModifierInspection.cs]: Does this create a new instance everytime the getter is called? If so then that would be a bug..
