### PR TITLE
Let declaration inspections use base classes

### LINKED ISSUE #5386: NullReferenceException in UnreachableCaseInspection
**Rubberduck version information**

```
Version 2.5.0.5336
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12430.20184
Host Executable: EXCEL.EXE
```

**Description**

Observed in the logs attached to #5385 (version information copied from there)

```
2020-02-13 13:41:06.1193;WARN-2.5.0.5336;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.GetIdentifierReferenceForContext(ParserRuleContext context, RubberduckParserState state) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 204
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.GetIdentifierReferenceForContext(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 197
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetIdentifierReferenceForContext(ParserRuleContext context, IdentifierReference& idRef) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 366
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 145
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 99
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 250
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitUnaryResultContext(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 235
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 115
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(IParseTree tree) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 59
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(IRuleNode node) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 70
   at Rubberduck.Parsing.Grammar.VBAParser.SelectCaseStmtContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 11962
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 153
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 105
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 179;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.GetIdentifierReferenceForContext(ParserRuleContext context, RubberduckParserState state) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 204
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.GetIdentifierReferenceForContext(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 197
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.TryGetIdentifierReferenceForContext(ParserRuleContext context, IdentifierReference& idRef) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 366
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(LExprContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 145
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 99
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(ParserRuleContext context) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 250
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitUnaryResultContext(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 235
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(ParserRuleContext parserRuleContext) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 115
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.Visit(IParseTree tree) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 59
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.ParseTreeValueVisitor.VisitChildren(IRuleNode node) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\ParseTreeValueVisitor.cs:line 70
   at Rubberduck.Parsing.Grammar.VBAParser.SelectCaseStmtContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 11962
   at Rubberduck.Inspections.Concrete.UnreachableCaseInspection.UnreachableCaseInspection.DoGetInspectionResults() in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Concrete\UnreachableCaseInspection\UnreachableCaseInspection.cs:line 153
   at Rubberduck.Inspections.Abstract.InspectionBase.GetInspectionResults(CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Abstract\InspectionBase.cs:line 105
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.RunInspection(IInspection inspection, ConcurrentBag`1 allIssues, CancellationToken token) in C:\projects\rubberduck\Rubberduck.CodeAnalysis\Inspections\Inspector.cs:line 179
```

**To Reproduce**

No reproduction has been reported, the error does not manifest for users (because it just means inspection results will be missing)

**Expected behavior**

An exception during the inspection process leads to incorrect results for the failing inspection. The inspection needs to not throw exceptions so it can work correctly :)

Note that this is in a different place compared to #4659 and therefore not a duplicate

### LINKED ISSUE #5389: False possitive: "Variable is used but not assigned" when assigned in a Sub
**Rubberduck version information**
Version 2.5.0.5338
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12607.20000
Host Executable: EXCEL.EXE

**Description**
When a variable is Dim'd, then assigned via a call to a Sub, passing the variable as a ByRef parameter, then referenced, the inspection return a false possitive "not assigned"

**To Reproduce**
MCVE 

```
Option Explicit

Public Sub Inspection_UsedNotAssigned()
    Dim MyVar As Variant
    
    ' Assign value
    MyFunc MyVar
    
    'use it
    Debug.Print MyVar
    
End Sub

Private Sub MyFunc(ByRef Param As Variant)
    Param = "!"
End Sub
```

**Expected behavior**
The ByRef call to the Sub should be recognised as an assignment.

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4222436/RubberduckLog.txt)

### PR DESCRIPTION
**Pull request by MDoerner**
Closes #5386
Closes #5389

This PR introduces base classes for inspections returning `DeclarationInspectionResult`s and makes all but two derive from these. The two exceptions are `ObsoleteTypeHintInspection`, which also returns `IdentifierReferenceResult`s, and `ProcedureCanBEWrittenAsFunctionInspection`, which is an `IParseTreeInspection` (These will be refactored in a future PR.).

I am not too happy how the base classes turned out since there are multiple ways in which they differ regarding the information passes around. There is the standard version, which just checks whether a declaration is a result and then builds a result only based on that, a version that generates some additional property for the results, which is also used for the generation of the result description, a version that gets some global information like settings once and passes that around as further information for the decision whether a declaration is a result and a version that combines the two special versions.

In addition to the base classes for declaration inspections, this PR replaces the use of a dynamic `PropertyBag` on the inspection results with generic subclasses of the inspection result classes whose additional properties have the generic type. Moreover, there is now a property `DisabledQuickFixes` on the `InspectionResultBase` holding the names of all disabled quick fixes instead of using a magic member on the property bag for this purpose.

Finally, the behaviour of some inspections has been changed a bit to either be more consistent or to fix bugs. The changes correspond to the changed/added tests. 

PS: Sorry for the large diff.

### CODE REVIEW

File: Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+            foreach (var projectDeclaration in finder.UserDeclarations(DeclarationType.Project))
+            {
+                if (projectDeclaration == null)
+                {
+                    continue;
+                }
+
+                var module = projectDeclaration.QualifiedModuleName;
+                results.AddRange(DoGetInspectionResults(module, finder, globalInformation));
```
Comment (Vogel612) [inline Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs]: This does not account for the option of module-dependent global information as you've enabled through the virtual `GlobalInformation(QMN, Finder)` overload. YAGNI dictates that this additional overload should be removed..

File: Rubberduck.CodeAnalysis/Inspections/Abstract/IdentifierReferenceInspectionBase.cs [hunk 2]
```diff
@@ -16,13 +16,72 @@ protected IdentifierReferenceInspectionBase(RubberduckParserState state)
...
+            {
+                if (moduleDeclaration == null)
+                {
+                    continue;
+                }
+
+                var module = moduleDeclaration.QualifiedModuleName;
+                results.AddRange(DoGetInspectionResults(module, finder));
+            }
+
```
Comment (Vogel612) [inline Rubberduck.CodeAnalysis/Inspections/Abstract/IdentifierReferenceInspectionBase.cs]: The other inspection base classes also iterated over all user defined Projects. Why does this not?

File: Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionBase.cs [hunk 3]
```diff
@@ -4,63 +4,81 @@
...
+
+        protected abstract (bool isResult, T properties) IsResultDeclarationWithAdditionalProperties(Declaration declaration, DeclarationFinder finder);
+        protected abstract string ResultDescription(Declaration declaration, T properties);
+
+        protected virtual ICollection<string> DisabledQuickFixes(Declaration declaration, T properties) => new List<string>();
+
+        protected override IEnumerable<IInspectionResult> DoGetInspectionResults(QualifiedModuleName module, DeclarationFinder finder)
+        {
+            var objectionableDeclarationsWithAdditionalProperties = RelevantDeclarationsInModule(module, finder)
+                    .Select(declaration => (declaration, IsResultDeclarationWithAdditionalProperties(declaration, finder)))
```
[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionBase.cs]: The thing here is that the implementations gather the properties on the way while determining whether a declaration is a result. Quite often, getting the properties later amounts to basically redoing everything done when determining whether there is a result in the first place.

File: Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionBaseBase.cs [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+            foreach (var projectDeclaration in finder.UserDeclarations(DeclarationType.Project))
+            {
+                if (projectDeclaration == null)
+                {
+                    continue;
+                }
+
+                var module = projectDeclaration.QualifiedModuleName;
+                results.AddRange(DoGetInspectionResults(module, finder));
+            }
```
[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionBaseBase.cs]: Ah, nice!

File: Rubberduck.CodeAnalysis/Inspections/Abstract/IdentifierReferenceInspectionBase.cs (hunk 2 above)
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/IdentifierReferenceInspectionBase.cs]: This base class is for identifier references inside modules. Since projects do not contain code directly, there cannot be identifier references in it.

The other base classes deal with declarations and projects have a project declaration, which is the target of some inspections.

File: Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs (hunk 1 above)
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs]: Sorry, I do not really follow what you think should be removed and also not why.

Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs]: I am really not sure what which method exactly we will not need.
However, let me elaborate on the overload of `GlobalInformation`. The idea behind it is not to provide different information by module, but to allow for performance enhancements in case it is cheaper to get the information relating to one module relative to getting everything. It is used in the overload of `DoGetInspectionResults` taking a QMN. That overload will become part of the `IInspection` in a future PR to allow running inspections for individual modules only.

File: Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionBase.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (MDoerner) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionBase.cs]: Regarding the naming of the tuple items: Thank You!
I was not aware that one can do that.

File: Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs (hunk 1 above)
Comment (Vogel612) [reply Rubberduck.CodeAnalysis/Inspections/Abstract/DeclarationInspectionUsingGlobalInformationBaseBase.cs]: then my original point is moot :)
