### PR TITLE
Port to castle windsor

### LINKED ISSUE #3287: Kill Ninject
Ninject has been identified as the root of all evil.

Removing Ninject has a few implications:

 - Abstract factories will need concrete implementations.
 - Bindings defined in `RubberduckModule` will need to be implemented manually (aka "Poor Man's DI"), until another DI/IoC framework is in place; we'll need to cleanly implement the composition root in the `Rubberduck.Root` namespace. This will be tedious, but definitely worth it.
 - Interceptors won't work anymore: we'll lose performance timing of individual inspections. As a side-effect the `GetType` method of inspection types will start returning actual inspection types instead of Castle Windsor proxy types... which makes the recently-added `Type` property moot.
 - Crash on exit: gone.
 - Major performance boost on startup.

### PR DESCRIPTION
**Pull request by MDoerner**
This PR ports the registration logic to Castle Windsor and makes some adjustments to the auto-magic factories because they work a bit different with CW.

I have strived to stay as close to the registration logic we had with Ninject but had to make some adjustments because there is no `WhenInjectedInto`. Moreover, I removed resolving the menu items during the registration in favour of letting the resolver do it when resolving the `App`. In addition, structured the registration logic a bit more. 
Another change is that the `GeneralSetting` we load at the startup to determine whether to display the splash window now get passed to the container. This is used to determine whether to load SC or not, at least regarding the menu item. (Before, the settings got resolved at the spot they were needed in the registration.)

Regarding startup speed, I could not see any improvement; it might actually be even slower.

Given the more structured registration module `RubberduckIoCInstaller` and the fact that the registration logic now works the way around it does for most IoC containers, porting again to another IoC container should be easier next time we feel the urge to do so.

Please have a look at the new registration and review closely. Due to the nature of the container, I could not test after every step I made. Still, all tests pass and it is F5 tested. (There has not been another way to test the registration anyway.) Moreover, now there are also some new tests testing that the registration does not blow up and that the same is true for resolving the `RubberduckParserstate` and the `Inspection`s.

Happy reviewing!

Closes #3287

### CODE REVIEW

File: Rubberduck.Inspections/QuickFixes/AssignedByValParameterMakeLocalCopyQuickFix.cs [hunk 1]
```diff
@@ -54,18 +54,24 @@ public override string Description(IInspectionResult result)
...
                 if (view.DialogResult == DialogResult.Cancel || !IsValidVariableName(view.NewName, forbiddenNames))
                 {
                     return string.Empty;
                 }
 
                 return view.NewName;
             }
+            finally
+            {
+                _dialogFactory.Release(view);
```
Comment (retailcoder) [inline Rubberduck.Inspections/QuickFixes/AssignedByValParameterMakeLocalCopyQuickFix.cs]: Do all factories need an explicit `Release` call? Not that I'm religious about it, but per Seemann's "RRR" pattern there should only need to be one single call to `Release` the container in the app. Calling `Release` on the factory instance seems counter-intuitive to me. It's releasing the `view`?

Comment (MDoerner) [reply Rubberduck.Inspections/QuickFixes/AssignedByValParameterMakeLocalCopyQuickFix.cs]: The thing why you call `factory.Release` with the auto-magic factories in CW is that CW tracks everything. If the `view` is registered in singleton scope, the release call does not do anything, at least I think so. However, if it is bound in transient scope, CW will dispose it, if disposable, and stop tracking it. Otherwise, it will hold on to a reference to the object until the container gets disposed.

**Comment by bclothier** [comment]
The additions of various `app.config` worries me -- they don't work quite the same way for a project that's basically a DLL. Should we really be using the default implementation of `app.config` to load the settings? Because Rubberduck gets loaded as a DLL, `app.config` might not work as expected. We would need to do something else to ensure that the `.config` files can be processed.

**Comment by MDoerner** [comment]
The `app.config` files have been added automatically when installing the CW package. I guess CW needs them and should find them since the package has added them.

File: RetailCoder.VBE/Root/RubberduckIoCInstaller.cs [hunk 2]
```diff
@@ -0,0 +1,841 @@
...
+                typeof(RefactorImplementInterfaceCommandMenuItem)
+            };
+        }
+
+        private static Type[] NavigateMenuItems()
+        {
+            return new Type[]
+            {
+                typeof(CodeExplorerCommandMenuItem),
+                //typeof(RegexSearchReplaceCommandMenuItem),
```
Comment (Vogel612) [inline RetailCoder.VBE/Root/RubberduckIoCInstaller.cs]: can this also be moved into an `#if DEBUG` block?

Comment (MDoerner) [reply RetailCoder.VBE/Root/RubberduckIoCInstaller.cs]: What exactly should be moved there: the `RegexSearchReplaceCommandMenuItem` but uncommented?

Comment (Vogel612) [reply RetailCoder.VBE/Root/RubberduckIoCInstaller.cs]: That would be more in line with the SerializeDeclarationsMenuItem and RefactorExtractMethodCommand bindings. @retailcoder @Hosch250  is the feature ready enough to not blow everything to pieces when we bind it for debug builds?

Comment (retailcoder) [reply RetailCoder.VBE/Root/RubberduckIoCInstaller.cs]: @Vogel612 no idea, @bclothier what do you say?

Comment (bclothier) [reply RetailCoder.VBE/Root/RubberduckIoCInstaller.cs]: For this PR, I'd leave ExtractMethod out. I'll make a note to update once I can merge.

Comment (MDoerner) [reply RetailCoder.VBE/Root/RubberduckIoCInstaller.cs]: Please note that removing a command menu item from the menus does __not__ cause the corresponding command not to be loaded; it only removes the menu item.
