### PR TITLE
Subclass All the Things! - Event rework to more reliably attach to windows.

### LINKED ISSUE #4080: CodePaneSubClass is only hooked on newly-created windows
Auto Complete will works only if I create a new object (module, form, etc), and only in that new object.

After saving, closing Access and reopen, the Auto Complete is not working for all objects.

I tested this on 3 different PC, with similar spec.

Logs:
```
2018-06-13 10:54:37.4033;TRACE-2.2.6737.8365;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.2.6737.8365 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.4963.1000
	Host Executable: MSACCESS.EXE;
2018-06-13 10:54:37.4253;TRACE-2.2.6737.8365;Rubberduck.App;Checking for legacy Smart Indenter settings.;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand was registered with id 49601;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorEncapsulateFieldCommand was registered with id 49596;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorMoveCloserToUsageCommand was registered with id 49602;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.CodeExplorerCommand was registered with id 49603;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ExportAllCommand was registered with id 49604;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.FindSymbolCommand was registered with id 49605;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentModuleCommand was registered with id 49606;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentProcedureCommand was registered with id 49607;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.InspectionResultsCommand was registered with id 49608;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ReparseCommand was registered with id 49609;
2018-06-13 10:54:37.6453;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.TestExplorerCommand was registered with id 49610;
2018-06-13 10:54:37.6693;INFO-2.2.6737.8365;Rubberduck.UI.Command.VersionCheckCommand;Executing version check.;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand was registered with id 49610;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorEncapsulateFieldCommand was registered with id 49609;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorMoveCloserToUsageCommand was registered with id 49608;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.CodeExplorerCommand was registered with id 49607;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ExportAllCommand was registered with id 49606;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.FindSymbolCommand was registered with id 49605;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentModuleCommand was registered with id 49604;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentProcedureCommand was registered with id 49603;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.InspectionResultsCommand was registered with id 49602;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ReparseCommand was registered with id 49596;
2018-06-13 10:54:42.5638;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.TestExplorerCommand was registered with id 49601;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand was registered with id 49601;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorEncapsulateFieldCommand was registered with id 49596;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorMoveCloserToUsageCommand was registered with id 49602;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.CodeExplorerCommand was registered with id 49603;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ExportAllCommand was registered with id 49604;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.FindSymbolCommand was registered with id 49605;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentModuleCommand was registered with id 49606;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentProcedureCommand was registered with id 49607;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.InspectionResultsCommand was registered with id 49608;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ReparseCommand was registered with id 49609;
2018-06-13 10:54:57.6933;TRACE-2.2.6737.8365;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.TestExplorerCommand was registered with id 49610;
```

### PR DESCRIPTION
**Pull request by comintern**
Closes #4080 and #3387 

This also lead to discovering what appears to be one underlying issue for #3472, but that one looks like it was always broken in how it handles CodePanes and Designers. That one should behave a little better now, but a "true fix" for that will come in another PR as it's slightly more involved.

Can PR comments have images?

subclass

Affirmative.

### CODE REVIEW

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 1]
```diff
@@ -49,6 +29,14 @@ public static void HookEvents(IVBE vbe)
                 }
                 _threadId = User32.GetWindowThreadProcessId(mainWindowHwnd, IntPtr.Zero);
                 _eventHandle = User32.SetWinEventHook((uint)WinEvent.Min, (uint)WinEvent.Max, IntPtr.Zero, _eventProc, 0, _threadId, WinEventFlags.OutOfContext);
+
+                var subclasses = mainWindowHwnd.ChildWindows()
+                    .Where(hwnd => SubclassManager.IsSubclassable(hwnd.ToWindowType()));
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Thinking that should be made a method on the `SubclassManager` to encapsulate the filters, so the calling code becomes simply `SubclassManager.AttachBulk(mainWindowHwnd.ChildWindows())`

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 2]
```diff
@@ -221,7 +167,7 @@ private static void OnWindowFocusChange(object sender, WindowChangedEventArgs ev
             WindowFocusChange?.Invoke(sender, eventArgs);
         } 
 
-        private static ICodePane GetCodePaneFromHwnd(IntPtr hwnd)
+        public static ICodePane GetCodePaneFromHwnd(IntPtr hwnd)
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Why can't this be a method or a ctor on the `ICodePane`?

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 3]
```diff
@@ -268,7 +214,7 @@ private static ICodePane GetCodePaneFromHwnd(IntPtr hwnd)
             }
         }
 
-        private static IWindow GetWindowFromHwnd(IntPtr hwnd)
+        public static IWindow GetWindowFromHwnd(IntPtr hwnd)
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Ditto for the `IWindow`. Maybe even consider make `ICodePane` and `IWindow` implement a `ISubclassable` interface?

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 4]
```diff
@@ -337,7 +278,7 @@ private static WindowType ToWindowType(this IntPtr hwnd)
 
         private static string ToClassName(this IntPtr hwnd)
         {
-            var name = new StringBuilder(128);
+            var name = new StringBuilder(255);
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Can we avoid magical number? Surely we defined the max length for the class name somewhere?

File: Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs [hunk 5]
```diff
@@ -1,61 +1,70 @@
...
+    //Stub for code pane replacement.  :-)
+    internal class CodePaneSubclass : FocusSource, IWindowEventProvider
     {
-        public static IntelliSenseEventArgs Shown => new IntelliSenseEventArgs(true);
-        public static IntelliSenseEventArgs Hidden => new IntelliSenseEventArgs(false);
-        internal IntelliSenseEventArgs(bool visible)
-        {
-            Visible = visible;
-        }
+        public event EventHandler<EventArgs> CaptionChanged;
```
Comment (bclothier) [inline Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs]: Looks like it should be just `EventHandler`

File: Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs [hunk 6]
```diff
@@ -1,61 +1,70 @@
...
-        public IntPtr Hwnd { get; }
-        public IntPtr WParam { get; }
-        public IntPtr LParam { get; }
-
-        public bool Handled { get; set; }
+        public bool HasValidCodePane
+        {
+            get
+            {
+                if (_codePane == null)
```
Comment (bclothier) [inline Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs]: Do we need to use `IsWrappingNullReference` here?

File: Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs [hunk 7]
```diff
@@ -1,61 +1,70 @@
...
-    {
-        public ICodePane CodePane { get; }
+                    _codePane.Dispose();
+                    _codePane = null;
+                }
+                catch
+                {
+                    // All paths leading to here mean that we need to ditch the held reference, and there
+                    // isn't jack all that we can do about it.
+                    _codePane = null;
```
Comment (bclothier) [inline Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs]: Actually we should stick in a `Debug.Warn` in here so that it'll show up in the log. Make the 🐦 go 🎤.

File: Rubberduck.VBEEditor/WindowsApi/IWindowEventProvider.cs [hunk 8]
```diff
@@ -5,7 +5,7 @@ namespace Rubberduck.VBEditor.WindowsApi
 {
     public interface IWindowEventProvider : IDisposable
     {
-        event EventHandler<WindowChangedEventArgs> FocusChange;
+        event EventHandler<EventArgs> CaptionChanged;
```
Comment (bclothier) [inline Rubberduck.VBEEditor/WindowsApi/IWindowEventProvider.cs]: Diito RE: `EventHandler`

File: Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs [hunk 9]
```diff
@@ -20,6 +21,33 @@ public IntPtr Handle()
...
+                {
+                    try
+                    {
+                        _unknown = Marshal.GetIUnknownForObject(Target);
+                        Marshal.Release(_unknown);
+                    }
+                    catch
+                    {
+                        // If GetIUnknownForObject threw us here, we're fine. If Marshal.Release threw us here, we're probably screwed
+                        // anyway, so we might as well just wait for the zombie process when the VBE tries to close.
```
Comment (bclothier) [inline Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs]: Same comment RE: `Debug.Warn` - it might be useful to know to show in the log that we got thrown here because of `Marhsal.Release` vs. `Marshal.GetIUnknownForObject` since the latter isn't necessarily a problem... *in theory*.

File: Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs [hunk 10]
```diff
@@ -1,7 +1,9 @@
 using System;
+using System.Collections.Generic;
 using System.IO;
 using System.Linq;
 using System.Text;
+using Microsoft.Office.Interop.MSProject;
```
Comment (bclothier) [inline Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs]: Should we be adding that?

File: Rubberduck.VBEditor.VBA/SafeComWrappers/VB/Window.cs [hunk 11]
```diff
@@ -20,6 +21,33 @@ public IntPtr Handle()
...
+                {
+                    try
+                    {
+                        _unknown = Marshal.GetIUnknownForObject(Target);
+                        Marshal.Release(_unknown);
+                    }
+                    catch
+                    {
+                        // If GetIUnknownForObject threw us here, we're fine. If Marshal.Release threw us here, we're probably screwed
+                        // anyway, so we might as well just wait for the zombie process when the VBE tries to close.
```
Comment (bclothier) [inline Rubberduck.VBEditor.VBA/SafeComWrappers/VB/Window.cs]: Ditto RE: `Debug.Warn` x3

File: Rubberduck.Core/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs [hunk 12]
```diff
@@ -57,15 +57,16 @@ private void EvaluateCanExecute(RubberduckParserState state, Declaration selecte
 
         private void OnSelectionChange(object sender, DeclarationChangedEventArgs e)
         {
-            var caption = e.ActivePane != null
-                ? _formatter.Format(e.ActivePane, e.Declaration)
-                : _formatter.Format(e.Declaration, e.MultipleControlsSelected);
+            //var caption = e.ActivePane != null
+            //    ? _formatter.Format(e.ActivePane, e.Declaration)
+            //    : _formatter.Format(e.Declaration, e.MultipleControlsSelected);
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.Core/UI/Command/MenuItems/CommandBars/RubberduckCommandBar.cs]: Thanks. I knew I missed some.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 13]
```diff
@@ -57,136 +45,94 @@ public static void UnhookEvents()
...
-        public static event EventHandler<SelectionChangedEventArgs> SelectionChanged;
+        public static event EventHandler<EventArgs> SelectionChanged;
         private static void OnSelectionChanged(IntPtr hwnd)
         {
             using (var pane = GetCodePaneFromHwnd(hwnd))
             {
                 if (pane != null)
                 {
-                    SelectionChanged?.Invoke(_vbe, new SelectionChangedEventArgs(pane));
+                    SelectionChanged?.Invoke(_vbe, new EventArgs());
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: I left that in as a placeholder. `SelectionChangedEventArgs` is going to get an implementation a couple PRs in the future. I should just change it back to the (empty) specific type.

File: Rubberduck.Core/UI/SelectionChangeService.cs [hunk 14]
```diff
@@ -33,47 +34,60 @@ public SelectionChangeService(IVBE vbe, IParseCoordinator parser)
...
             if (e.EventType == FocusType.GotFocus)
             {
-                switch (e.Window.Type)
+                switch (e.Hwnd.ToWindowType())
                 {
-                    case WindowKind.Designer:
-                        //Designer or control on designer form selected.
-                        if (e.Window == null || e.Window.IsWrappingNullReference || e.Window.Type != WindowKind.Designer)
+                    case WindowType.DesignerWindow:
+                        new Task(() =>
```
[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.Core/UI/SelectionChangeService.cs]: I'm not sure if case 1 is possible at this point in that the only thing that the `SelectionChangeService` is driving is the toolbar. It *might* be a problem if it is eventually wired up to something that changes the selection.

As for case 2, given the current use the only implication that would have would be flicker? on the toobar as the selection switches back and forth.

Note that the reason these are spun off into tasks is because this isn't on the UI thread.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 1 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Nice. Consider it done.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 2 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: The issue there is that in order to get subclasses established as soon as possible, we're attaching them *way* before the VBE objects are ready to handle requests. That's also the reason why the `CodePaneSubclass` was changed to allow lazy association with its `ICodePane`.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 3 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Ditto above. `DesignerWindowSubclass` is eventually going to need an `IWindow` member. `ISubclassable` might not be a bad idea, but that implementation feeds into the fragmentation of the code due to having both a VBA and VB6 assembly mirroring one another. Also, in that the message pumps are different, `ISubclassable` really isn't an accurate abstraction - `IWindow` should only be subclassed by a `DesignerWindowSubclass` and `ICodePane` should only be subclassed by a `CodePaneSubclass`.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 4 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Yep. I'll fix that. IIR it's a constant in the Windows headers somewhere.

File: Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs (hunk 6 above)
Comment (comintern) [reply Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs]: Don't think so. The only thing that `CodePaneSubclass` cares about is whether *it* has a reference. In fact, it should never be used from inside the class because it would be attempting to communicate with itself from inside its own message pump.  That might need a comment\warning.

File: Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs (hunk 7 above)
Comment (comintern) [reply Rubberduck.VBEEditor/WindowsApi/CodePaneSubclass.cs]: Done.

File: Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs (hunk 9 above)
Comment (comintern) [reply Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs]: Hmmm... I'd take suggestions on the wording for that. AFAICT there isn't a way to delineate what went wrong there. Should I nest the 2 calls in the `try` and `catch` each one individually?

File: Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs (hunk 10 above)
Comment (comintern) [reply Rubberduck.VBEditor.VBA/SafeComWrappers/VB/VBComponent.cs]: WTH did that come from? Deleted.

File: Rubberduck.Core/UI/SelectionChangeService.cs [hunk 15]
```diff
@@ -33,47 +34,60 @@ public SelectionChangeService(IVBE vbe, IParseCoordinator parser)
             VBENativeServices.WindowFocusChange += OnVbeFocusChanged;
         }
         
-        private void OnVbeSelectionChanged(object sender, SelectionChangedEventArgs e)
+        private void OnVbeSelectionChanged(object sender, EventArgs e)
```
Comment (Vogel612) [inline Rubberduck.Core/UI/SelectionChangeService.cs]: why the despecialization? Hasn't been done for `OnVbeFocusChanged`

File: Rubberduck.Core/UI/SelectionChangeService.cs [hunk 16]
```diff
@@ -33,47 +34,60 @@ public SelectionChangeService(IVBE vbe, IParseCoordinator parser)
...
+                        new Task(() =>
                         {
-                            new Task(() => DispatchSelectedDeclaration(new DeclarationChangedEventArgs(e.CodePane, _parser.State.FindSelectedDeclaration(e.CodePane)))).Start(); 
-                        }
+                            using (var pane = VBENativeServices.GetCodePaneFromHwnd(e.Hwnd))
+                            {
+                                DispatchSelectedDeclaration(
+                                    new DeclarationChangedEventArgs(_parser.State.FindSelectedDeclaration(pane)));
+                            }
+                        }).Start();
```
Comment (Vogel612) [inline Rubberduck.Core/UI/SelectionChangeService.cs]: why not `Task.Run(() => ...)`? That sidesteps the explicit `Start` and constructor

File: Rubberduck.Core/UI/SelectionChangeService.cs [hunk 17]
```diff
@@ -33,47 +34,60 @@ public SelectionChangeService(IVBE vbe, IParseCoordinator parser)
...
             {
                 //Treeview selection changed in project window.
-                new Task(() => DispatchSelectedProjectNodeDeclaration(_vbe.SelectedVBComponent)).Start();
+                new Task(() =>
+                {
+                    using (var component = _vbe.SelectedVBComponent)
+                    {
+                        DispatchSelectedProjectNodeDeclaration(component);
+                    }
+                }).Start();
```
Comment (Vogel612) [inline Rubberduck.Core/UI/SelectionChangeService.cs]: same as before re: task creation

File: Rubberduck.Core/UI/SelectionChangeService.cs [hunk 18]
```diff
@@ -176,17 +193,12 @@ public void Dispose()
...
-        public ICodePane ActivePane { get; private set; }
-        public Declaration Declaration { get; private set; }
-        // ReSharper disable once InconsistentNaming
-        public IVBComponent VBComponent { get; private set; }
-        public bool MultipleControlsSelected { get; private set; }
+        public Declaration Declaration { get; }
+        public bool MultipleControlsSelected { get; }
 
-        public DeclarationChangedEventArgs(ICodePane pane, Declaration declaration, IVBComponent component = null, bool multipleControls = false)
+        public DeclarationChangedEventArgs(Declaration declaration, bool multipleControls = false)
```
Comment (Vogel612) [inline Rubberduck.Core/UI/SelectionChangeService.cs]: oouuuh nice! simplifications 👍

File: Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs [hunk 19]
```diff
@@ -136,41 +136,44 @@ private IEnumerable<IAnnotation> FindAnnotations(int line)
...
-                if (msFormsLib != null)
+                if (controls == null) { return; }
+
+                var libraryQualifier = string.Empty;
+                if (_qualifiedModuleName.ComponentType == ComponentType.UserForm)
                 {
-                    // given a UserForm component, MSForms reference is in use and cannot be removed.
-                    libraryQualifier = "MSForms.";
+                    var msFormsLib = _state.DeclarationFinder.FindProject("MSForms");
+                    //Debug.Assert(msFormsLib != null);
```
Comment (Vogel612) [inline Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs]: commented code. we explicitly check that assertion now. remove?

File: Rubberduck.VBEEditor/Events/EventArgs/KeyPressEventArgs.cs [hunk 20]
```diff
@@ -0,0 +1,34 @@
+﻿using System;
+using System.Windows.Forms;
+
+namespace Rubberduck.VBEditor.Events
+{
+    public class KeyPressEventArgs
+    {
+        public KeyPressEventArgs(IntPtr hwnd, IntPtr wParam, IntPtr lParam, char character = default)
```
Comment (Vogel612) [inline Rubberduck.VBEEditor/Events/EventArgs/KeyPressEventArgs.cs]: you should maybe explain why we are reinventing the WindowsApi.KeyPressEventArgs here

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 21]
```diff
@@ -57,136 +45,94 @@ public static void UnhookEvents()
...
+        }
+
         public static void VbeEventCallback(IntPtr hWinEventHook, uint eventType, IntPtr hwnd, int idObject, int idChild,
             uint dwEventThread, uint dwmsEventTime)
         {
             if (hwnd == IntPtr.Zero) { return; }
-            //This is an output window firehose, leave this here, but comment it out when done.
-            //if (idObject != (int)ObjId.Cursor) { Debug.WriteLine("Hwnd: {0:X4} - EventType {1:X4}, idObject {2}, idChild {3}", (int)hwnd, eventType, idObject, idChild); }
 
+#if THIRSTY_DUCK
```
Comment (Vogel612) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: lol for that compilation flag name. Do we need to explicitly set it? Should we maybe also check for `DEBUG` having been set?

File: Rubberduck.VBEEditor/HashCode.cs [hunk 22]
```diff
@@ -21,5 +23,10 @@ public static int Compute(params object[] values)
                 return hash;
             }
         }
+
+        public static int Compute(IEnumerable<int> values)
+        {
+            return values.Aggregate(5381, (hash, value) => ((hash << 5) + hash) ^ value);
```
Comment (Vogel612) [inline Rubberduck.VBEEditor/HashCode.cs]: oh, fancy hashing util there.

File: Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj [hunk 23]
```diff
@@ -93,14 +95,14 @@
...
-    <Compile Include="Events\ComponentEventArgs.cs" />
-    <Compile Include="Events\ComponentRenamedEventArgs.cs" />
-    <Compile Include="Events\ProjectEventArgs.cs" />
-    <Compile Include="Events\ProjectRenamedEventArgs.cs" />
-    <Compile Include="Events\SelectionChangedEventArgs.cs" />
+    <Compile Include="Events\EventArgs\ComponentEventArgs.cs" />
+    <Compile Include="Events\EventArgs\ComponentRenamedEventArgs.cs" />
+    <Compile Include="Events\EventArgs\ProjectEventArgs.cs" />
+    <Compile Include="Events\EventArgs\ProjectRenamedEventArgs.cs" />
+    <Compile Include="Events\EventArgs\SelectionChangedEventArgs.cs" />
```
Comment (Vogel612) [inline Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj]: I'm not really a fan of grouping classes by what thing they are. One of the express goals of the Ducky is to allow grouping and organizing user code by something else than the type of component it happens to be in ... that said, I see this is semi-historical. Might be something to clean up in the future, though

File: Rubberduck.VBEEditor/WindowsApi/DesignerWindowSubclass.cs [hunk 24]
```diff
@@ -16,8 +16,11 @@ public override int SubClassProc(IntPtr hWnd, IntPtr msg, IntPtr wParam, IntPtr
             {
                 DispatchFocusEvent(FocusType.GotFocus);
             }
-            //This is an output window firehose, leave this here, but comment it out when done.
-            //Debug.WriteLine("WM: {0:X4}, wParam {1}, lParam {2}", msg, wParam, lParam);
+
+#if THIRSTY_DUCK
```
Comment (Vogel612) [inline Rubberduck.VBEEditor/WindowsApi/DesignerWindowSubclass.cs]: again: possibly check for the DEBUG flag having been set as well

File: Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs (hunk 9 above)
Comment (Vogel612) [reply Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs]: if we can ignore the exception for one of the use-cases, then we should separate that from a possibly fatal error

Comment (comintern) [reply Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs]: @Vogel612  - it shouldn't be "fatal" in the sense that it will bring the process down, but I agree - I'll nest the `try`s.

File: Rubberduck.Core/UI/SelectionChangeService.cs (hunk 15 above)
Comment (comintern) [reply Rubberduck.Core/UI/SelectionChangeService.cs]: @Vogel612 See [this comment](https://github.com/rubberduck-vba/Rubberduck/pull/4240#discussion_r206311809). I'm re-specializing this and I apparently forgot to stub the `SelectionChangedEventArgs`, so I caught that too.

File: Rubberduck.Core/UI/SelectionChangeService.cs (hunk 17 above)
Comment (comintern) [reply Rubberduck.Core/UI/SelectionChangeService.cs]: Because apparently I'm an idiot. :-)  Fixed.

File: Rubberduck.VBEEditor/Events/EventArgs/KeyPressEventArgs.cs (hunk 20 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/EventArgs/KeyPressEventArgs.cs]: Not mine, just moved it there. It passes the arguments from the window proc though. Commented.

File: Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs (hunk 19 above)
Comment (comintern) [reply Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs]: Done.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 21 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: I must not have been thirsty enough to check that on a release build... Fixed.

File: Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj (hunk 23 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Rubberduck.VBEditor.csproj]: I wasn't really sure where else to put them. I was finding them attached to class implementations all over the place and thought they'd be easier to track down this way. I'm open to suggestions as to where they belong, but I was finding that it added a lot of cognitive load when they were in the same file as the declaring events.

File: Rubberduck.VBEEditor/Events/EventArgs/KeyPressEventArgs.cs (hunk 20 above)
Comment (retailcoder) [reply Rubberduck.VBEEditor/Events/EventArgs/KeyPressEventArgs.cs]: That was me. This was introduced for AC to pick up both WM_CHAR and WM_KEYPRESS - the former gives us the typed characters, the latter a WinForms.Keys enum for non-characters, e.g. BACKSPACE. There's no reliable or obvious mapping between the WM_CHAR lparam and WinForms.Keys, so I folded both into this one.

File: Rubberduck.Core/UI/SelectionChangeService.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (bclothier) [reply Rubberduck.Core/UI/SelectionChangeService.cs]: Wait a minute; you want to run them on the UI thread? If that's the case, we should be using `UiDispatcher` here. 

As the comments - I'm thinking that the subclassing event handling needs to be handled in a general manner that is unlikely to cause problems for any potential consumers, as I expect that we will expand more and more beyond the AC, the status tool, whatever. So I'm thinking we want it to be quite robust and won't trip over its own feet even if we shoot our feet in trying to do so. 😆

[the remark this answers is not in the document]
Comment (comintern) [reply Rubberduck.Core/UI/SelectionChangeService.cs]: @bclothier Hmmm... that's a catch 22 then. If we want this handled in a general manner, we probably *shouldn't* use the `UiDispatcher`, no?  Regardless, if these are blocking that's a ***big*** problem due to the amount of traffic through here.

I don't disagree with the need to make this more robust though, but I think that can be addressed when we expand beyond AC and the toolbar. It won't be our feet that we shoot - it will be much higher...

[the remark this answers is not in the document]
Comment (bclothier) [reply Rubberduck.Core/UI/SelectionChangeService.cs]: Agreed that we don't want it on UI thread at all; running the task in their own thread is probably best overall, but because I can see events firing so frequently and so rapidly, we will see weird things if we don't manage that and for that reason, one task per event raised might not be the optimal strategy. Consider also that `Task` are known to re-use threads which may have its own ramifications as well. #BeltsAndSuspenders

File: Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs [hunk 25]
```diff
@@ -35,13 +35,21 @@ public IntPtr IUnknown
...
-                        _unknown = Marshal.GetIUnknownForObject(Target);
+                        try
+                        {
+                            _unknown = Marshal.GetIUnknownForObject(Target);
+                        }
+                        catch
+                        {
+                            // If GetIUnknownForObject throws us here, we're fine - it just means that the wrapper itself is invalid.
+                        }
                         Marshal.Release(_unknown);
```
Comment (bclothier) [inline Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs]: I don't think it's appropriate to call `Marshal.Release` after an exception. I'd presume that in such case, the `_unknown` will be `IntPtr.Zero` or something like that and that would be might bad to try and release a null pointer.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 26]
```diff
@@ -57,136 +40,94 @@ public static void UnhookEvents()
...
             {
                 User32.UnhookWinEvent(_eventHandle);
-                foreach (var info in TrackedWindows.Values)
-                {
-                    info.Subclass.FocusChange -= FocusDispatcher;
-                    info.Subclass.Dispose();
-                }
+                Subclasses.Dispose();
                 VBEEvents.Terminate();
+                _vbe.Dispose();
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: I don't think this is appropriate. If you [look here](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Main/Extension.cs#L237), you can see we are still using the `_vbe` after we call the `UnhookEvents`. I'm not even sure if it's appropriate to dispose the `_vbe`, since it was handed to us from the addin.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs [hunk 27]
```diff
@@ -57,136 +40,94 @@ public static void UnhookEvents()
...
+            //This is an output window firehose, viewer discretion is advised.
+            if (idObject != (int)ObjId.Cursor) { Debug.WriteLine("Hwnd: {0:X4} - EventType {1:X4}, idObject {2}, idChild {3}", (int)hwnd, eventType, idObject, idChild); }
+#endif
             var windowType = hwnd.ToWindowType();
-            var nameBuilder = new StringBuilder(255);
-            User32.GetClassName(hwnd, nameBuilder, 255);
-            var className = nameBuilder.ToString();
 
-            if (className == "NameListWndClass")
+            if (windowType == WindowType.IntelliSense)
```
Comment (bclothier) [inline Rubberduck.VBEEditor/Events/VBENativeServices.cs]: I wonder if it is worthwhile to broadcast a event rather than maintaining a long list of `if`/`else if`s for unrelated classes. The `Subclassable` could be required to implement a delegate which would be then added to a list, and thus enumerated instead.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 26 above)
Comment (MDoerner) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: I can only agree. Please do not dispose the VBE instance passed in via `HookEvents`. It is managed by the caller of that method, i.e. by the `Extension` class, our entry and exit point.

Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: Not sure what I was thinking there. Removed.

File: Rubberduck.VBEEditor/Events/VBENativeServices.cs (hunk 27 above)
Comment (comintern) [reply Rubberduck.VBEEditor/Events/VBENativeServices.cs]: The `VbeEventCallback` it there for handling application (VBE) level events that aren't tied to specific windows. The more important parameters are the `eventType` and `idObject` - I only grab the `windowType` before the `if`/`else if`s because it's used in multiple tests and it involves an API call.

The IntelliSense window isn't subclassed (I'm assuming this event filter is for autocomplete), and it wouldn't really be practical to do so. I haven't really explored it because I'd just assumed it was being continually recycled. 

The only other test performed here that is related to a specific window that can be assumed to be subclassed is the caret change notification. The reason that one is being performed at the VBE level is because it doesn't show up as cleanly in the individual windows' message pumps. About the only way to pick that out cleanly in the `CodePaneSubclass` is to listen for the "blinking" of the caret and then check its position against the last known caret position. That would be much more complex and unreliable.

File: Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs (hunk 25 above)
Comment (comintern) [reply Rubberduck.VBEditor.VB6/SafeComWrappers/VB/Window.cs]: :facepalm:  @bclothier - I just realized that these aren't used anymore (I abandoned that approach as unreliable). Removing them from the interface instead.

File: Rubberduck.VBEEditor/WindowsApi/VbeAttachableSubclass.cs [hunk 28]
```diff
@@ -47,20 +47,24 @@ public bool HasValidVbeObject
...
+                    if (unmanaged != IntPtr.Zero)
                     {
+                        try
+                        {
+                            Marshal.Release(unmanaged);
+                        }
+                        catch (COMException)
+                        {
+                            // this should be "safe" to hold the reference - it's not like it should go anywhere now... :-/
+                            SubclassLogger.Warn($"{ GetType().Name } failed to dispose of a held { typeof(T).Name } reference.");
```
Comment (bclothier) [inline Rubberduck.VBEEditor/WindowsApi/VbeAttachableSubclass.cs]: The log message doesn't actually reflect what really just happened. Probably should be `...failed to release unmanaged pointer {unmanaged} of a held....` or something like that.

Comment (comintern) [reply Rubberduck.VBEEditor/WindowsApi/VbeAttachableSubclass.cs]: It isn't attempting to release the *pointer*, `Marshal.Release` attempts to call `.Release` on the `IUnknown` pointed to by the pointer in order to decrement its reference count. Documentation is [here](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.release(v=vs.110).aspx).

Comment (comintern) [reply Rubberduck.VBEEditor/WindowsApi/VbeAttachableSubclass.cs]: ...although I can see how "dispose of" implies `IDisposable`.  What about:

`failed to decrement reference count of a held { typeof(T).Name } reference`

Comment (bclothier) [reply Rubberduck.VBEEditor/WindowsApi/VbeAttachableSubclass.cs]: Better. 👍
